import { useState } from 'react';
import type { EvidenceItem } from '../types';
import { FileText, Download, Shield, Scale, Mic, AlertCircle, CheckCircle, Check } from 'lucide-react';
import { useToast } from './Toast';

const TYPE_ICONS: Record<string, typeof FileText> = {
  ALERT: AlertCircle,
  VOICE: Mic,
  FINANCIAL: Shield,
  LEGAL: Scale,
  NCRB: FileText,
  ANALYSIS: CheckCircle,
};

const TYPE_COLORS: Record<string, string> = {
  ALERT: '#f43f5e',
  VOICE: '#3b82f6',
  FINANCIAL: '#f59e0b',
  LEGAL: '#8b5cf6',
  NCRB: '#10b981',
  ANALYSIS: '#3b82f6',
};

export default function EvidencePackage({ items }: { items: EvidenceItem[] }) {
  const { addToast } = useToast();
  const [exported, setExported] = useState(false);

  const handleExport = () => {
    let content = 'RAKSHA AI — EVIDENCE PACKAGE\n';
    content += `Generated: ${new Date().toISOString()}\n`;
    content += '='.repeat(60) + '\n\n';
    items.forEach((item) => {
      content += `[${item.type}] ${item.title}\n`;
      content += '-'.repeat(40) + '\n';
      content += item.content + '\n\n';
    });
    content += '='.repeat(60) + '\n';
    content += 'This evidence package was generated by RAKSHA AI Intelligence System.\n';
    content += 'For legal admissibility, refer to IT Act Section 65B compliance.\n';
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `raksha-ai-evidence-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setExported(true);
    addToast('Evidence package exported successfully', 'success');
    setTimeout(() => setExported(false), 2000);
  };

  if (items.length === 0) return null;

  return (
    <div className="space-y-2.5 sm:space-y-3">
      <div className="flex items-center justify-between gap-2">
        <h3 className="font-mono text-[10px] sm:text-xs font-medium tracking-wider text-zinc-500 uppercase">
          Evidence Package
        </h3>
        <button onClick={handleExport}
          className="flex items-center gap-1 sm:gap-1.5 px-2.5 sm:px-3 py-1.5 rounded-lg font-mono text-[10px] sm:text-xs font-medium touch-target btn-premium btn-ripple flex-shrink-0 relative overflow-hidden"
          style={{ background: 'rgba(59,130,246,0.08)', color: '#3b82f6', border: '1px solid rgba(59,130,246,0.2)' }}>
          {exported ? (
            <>
              <Check size={10} strokeWidth={2} />
              <span className="hidden sm:inline">Exported</span>
              <span className="sm:hidden">Done</span>
            </>
          ) : (
            <>
              <Download size={10} strokeWidth={1.5} />
              <span className="hidden sm:inline">Export Package</span>
              <span className="sm:hidden">Export</span>
            </>
          )}
        </button>
      </div>
      <div className="space-y-1.5 sm:space-y-2">
        {items.map((item, i) => {
          const Icon = TYPE_ICONS[item.type] || FileText;
          const color = TYPE_COLORS[item.type] || '#52525b';
          return (
            <div key={i}
              className="animate-fade-slide-up p-3 sm:p-4 rounded-xl border card-hover"
              style={{
                animationDelay: `${i * 60}ms`,
                animationFillMode: 'both',
                backgroundColor: `${color}06`,
                borderColor: `${color}18`,
              }}>
              <div className="flex items-center gap-1.5 sm:gap-2 mb-1.5 sm:mb-2">
                <Icon size={12} style={{ color }} className="flex-shrink-0" />
                <span className="font-mono text-[10px] sm:text-[11px] font-medium truncate" style={{ color }}>{item.title}</span>
                <span className="ml-auto font-mono text-[8px] sm:text-[10px] px-1.5 sm:px-2 py-0.5 rounded-full flex-shrink-0"
                  style={{ backgroundColor: `${color}12`, color }}>{item.type}</span>
              </div>
              <p className="text-[10px] sm:text-xs text-zinc-300 leading-relaxed">{item.content}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
