import type { EvidenceItem } from '../types';
import { FileText, Download, Shield, Scale, Mic, AlertCircle, CheckCircle } from 'lucide-react';

const TYPE_ICONS: Record<string, typeof FileText> = {
  ALERT: AlertCircle,
  VOICE: Mic,
  FINANCIAL: Shield,
  LEGAL: Scale,
  NCRB: FileText,
  ANALYSIS: CheckCircle,
};

const TYPE_COLORS: Record<string, string> = {
  ALERT: '#FF3B4E',
  VOICE: '#22D3EE',
  FINANCIAL: '#FBBF24',
  LEGAL: '#A78BFA',
  NCRB: '#34D399',
  ANALYSIS: '#22D3EE',
};

export default function EvidencePackage({ items }: { items: EvidenceItem[] }) {
  const handleExport = () => {
    let content = 'RAKSHA AI — EVIDENCE PACKAGE\n';
    content += `Generated: ${new Date().toISOString()}\n`;
    content += '='.repeat(60) + '\n\n';
    items.forEach((item) => {
      content += `[${item.type}] ${item.title}\n`;
      content += '-'.repeat(40) + '\n';
      content += item.content + '\n\n';
    });
    content += '='.repeat(60) + '\n';
    content += 'This evidence package was generated by RAKSHA AI Intelligence System.\n';
    content += 'For legal admissibility, refer to IT Act Section 65B compliance.\n';

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `raksha-ai-evidence-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (items.length === 0) return null;

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="font-mono text-xs font-semibold tracking-wider text-[#6B7280] uppercase">
          Evidence Package
        </h3>
        <button
          onClick={handleExport}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-md font-mono text-xs font-semibold
            bg-[#22D3EE]/10 text-[#22D3EE] border border-[#22D3EE]/30
            hover:bg-[#22D3EE]/20 hover:border-[#22D3EE]/50
            hover:scale-[1.02] hover:shadow-[0_0_12px_rgba(34,211,238,0.2)]
            transition-all duration-150"
        >
          <Download size={12} />
          Export Package
        </button>
      </div>
      <div className="space-y-2">
        {items.map((item, i) => {
          const Icon = TYPE_ICONS[item.type] || FileText;
          const color = TYPE_COLORS[item.type] || '#6B7280';
          return (
            <div
              key={i}
              className="animate-fade-slide-up p-4 rounded-2xl border"
              style={{
                animationDelay: `${i * 60}ms`,
                animationFillMode: 'both',
                backgroundColor: `${color}06`,
                borderColor: `${color}20`,
              }}
            >
              <div className="flex items-center gap-2 mb-2">
                <Icon size={14} style={{ color }} />
                <span className="font-mono text-[11px] font-semibold" style={{ color }}>
                  {item.title}
                </span>
                <span
                  className="ml-auto font-mono text-[10px] px-2 py-0.5 rounded-full"
                  style={{ backgroundColor: `${color}15`, color }}
                >
                  {item.type}
                </span>
              </div>
              <p className="text-xs text-[#E5E7EB]/80 leading-relaxed">
                {item.content}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
