import { useState } from 'react';
import { Download, Copy, Printer, Share2, Check } from 'lucide-react';
import type { TranscriptScenario } from '../types';
import { useToast } from './Toast';

function buildReport(scenario: TranscriptScenario): string {
  let report = '═══════════════════════════════════════════════════\n';
  report += '         RAKSHA AI — SCAM ANALYSIS REPORT\n';
  report += `         Generated: ${new Date().toLocaleString()}\n`;
  report += '═══════════════════════════════════════════════════\n\n';

  report += `SCENARIO: ${scenario.label}\n`;
  report += `DESCRIPTION: ${scenario.description}\n`;
  report += `RISK LEVEL: ${scenario.riskLevel}\n`;
  report += `RISK SCORE: ${scenario.finalScore}/100\n\n`;

  report += '── TRANSCRIPT ──────────────────────────────────────\n';
  scenario.transcript.forEach((line) => {
    report += `[${line.speaker}]: ${line.text}\n`;
  });
  report += '\n';

  report += '── RED FLAGS ───────────────────────────────────────\n';
  scenario.redFlags.forEach((flag) => {
    report += `• [${flag.severity}] ${flag.phrase} (${flag.category})\n`;
  });
  report += '\n';

  report += '── EVIDENCE ────────────────────────────────────────\n';
  scenario.evidencePackage.forEach((item) => {
    report += `• [${item.type}] ${item.title}\n  ${item.content}\n\n`;
  });

  report += '── AI ANALYSIS ─────────────────────────────────────\n';
  report += `Scam Probability: ${scenario.aiAnalysis.scamProbability}%\n`;
  report += `Confidence: ${scenario.aiAnalysis.confidence}%\n`;
  report += `Threat Category: ${scenario.aiAnalysis.threatCategory}\n`;
  report += `${scenario.aiAnalysis.deepReasoning}\n\n`;

  report += '═══════════════════════════════════════════════════\n';
  report += '  Report generated by RAKSHA AI Intelligence System\n';
  report += '  For legal admissibility, refer to IT Act Section 65B\n';
  report += '═══════════════════════════════════════════════════\n';

  return report;
}

export default function ExportPanel({ scenario, analyzed }: { scenario: TranscriptScenario | null; analyzed: boolean }) {
  const { addToast } = useToast();
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);

  const disabled = !analyzed || !scenario;

  const markCopied = (idx: number) => {
    setCopiedIdx(idx);
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const handleDownload = () => {
    if (disabled || !scenario) return;
    try {
      const report = buildReport(scenario);
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `raksha-ai-report-${Date.now()}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      addToast('Report downloaded successfully', 'success');
      markCopied(0);
    } catch {
      addToast('Failed to download report', 'error');
    }
  };

  const handleCopy = async () => {
    if (disabled || !scenario) return;
    try {
      const report = buildReport(scenario);
      await navigator.clipboard.writeText(report);
      addToast('Report copied to clipboard', 'success');
      markCopied(1);
    } catch {
      addToast('Failed to copy report', 'error');
    }
  };

  const handlePrint = () => {
    if (disabled) return;
    window.print();
    addToast('Print dialog opened', 'success');
  };

  const handleShare = async () => {
    if (disabled || !scenario) return;
    try {
      const msg = `🛡️ RAKSHA AI Scam Report\n\nScenario: ${scenario.label}\nRisk: ${scenario.riskLevel} (${scenario.finalScore}/100)\nCategory: ${scenario.aiAnalysis.threatCategory}\n\nAnalyzed by RAKSHA AI — Intelligent Scam Detection`;
      await navigator.clipboard.writeText(msg);
      addToast('Share message copied to clipboard', 'success');
      markCopied(3);
    } catch {
      addToast('Failed to copy share link', 'error');
    }
  };

  const actions = [
    { icon: Download, label: 'Download TXT', onClick: handleDownload },
    { icon: copiedIdx === 1 ? Check : Copy, label: copiedIdx === 1 ? 'Copied!' : 'Copy to Clipboard', onClick: handleCopy },
    { icon: Printer, label: 'Print Report', onClick: handlePrint },
    { icon: Share2, label: 'Share Link', onClick: handleShare },
  ];

  return (
    <div className="space-y-3 sm:space-y-4">
      <div className="flex items-center gap-2">
        <Download size={16} className="text-blue-400" />
        <h3 className="font-mono text-[10px] sm:text-xs font-medium tracking-wider text-zinc-500 uppercase">Export Report</h3>
      </div>

      <div className="grid grid-cols-2 gap-2.5 sm:gap-3">
        {actions.map((action, i) => {
          const Icon = action.icon;
          return (
            <button
              key={i}
              onClick={action.onClick}
              disabled={disabled}
              className="animate-fade-slide-up btn-ripple p-3.5 sm:p-4 rounded-xl border bg-white/[0.03] border-white/[0.06] flex flex-col items-center gap-2.5 transition-all duration-200 hover:bg-white/[0.06] hover:translate-y-[-1px] disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:translate-y-0 disabled:hover:bg-white/[0.03]"
              style={{ animationDelay: `${i * 60}ms`, animationFillMode: 'both' }}
            >
              <Icon size={18} className={copiedIdx === i ? 'text-green-400' : 'text-zinc-400'} />
              <span className="font-mono text-[10px] sm:text-[11px] font-medium text-zinc-400 text-center leading-tight">{action.label}</span>
            </button>
          );
        })}
      </div>
    </div>
  );
}
