import type { TranscriptScenario } from './types';

export const SCENARIO_BATCH_3: TranscriptScenario[] = [
  {
    id: 'insurance-scam',
    label: 'Fake Insurance Policy Scam',
    description: 'Scammer calls posing as an SBI Life Insurance agent claiming the victim\'s policy is about to lapse and demands immediate payment to maintain coverage.',
    transcript: [
      { speaker: 'Scammer', text: 'Namaste, this is Rajesh Sharma calling from SBI Life Insurance. Your policy number SBIL-4478921 is due for renewal tomorrow. If you don\'t pay the premium of 12,500 rupees today, your coverage will be permanently cancelled.' },
      { speaker: 'Victim', text: 'I think my premium is auto-debited from my account. Let me check.' },
      { speaker: 'Scammer', text: 'Sir, the auto-debit failed because your bank account has a new KYC requirement. You must pay immediately through UPI to avoid lapse. I will send you a Google Pay QR code.' },
      { speaker: 'Victim', text: 'Can you send me an official email first?' },
      { speaker: 'Scammer', text: 'There is no time for email, sir. The policy lapses at 6 PM today. I am sending you a UPI ID now — pay immediately or lose 5 lakh coverage.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 75,
    redFlags: [
      { phrase: 'Policy lapses today', category: 'Urgency pressure', severity: 'HIGH' },
      { phrase: 'Pay through UPI immediately', category: 'Unusual payment method', severity: 'CRITICAL' },
      { phrase: 'Auto-debit failed due to KYC', category: 'Fabricated technical issue', severity: 'HIGH' },
      { phrase: 'No time for email', category: 'Preventing verification', severity: 'HIGH' },
      { phrase: 'QR code for payment', category: 'Unofficial payment channel', severity: 'CRITICAL' },
      { phrase: 'Lose 5 lakh coverage', category: 'Fear-based manipulation', severity: 'MEDIUM' },
    ],
    agentFires: [
      { agent: 'PolicyVerifier', action: 'Cross-referenced policy number SBIL-4478921 with SBI Life database — record not found', timestamp: '00:01:22', triggeredBy: 'Policy number mentioned' },
      { agent: 'VoiceAnalyzer', action: 'Detected urgency manipulation pattern — caller escalating pressure every 15 seconds', timestamp: '00:01:45', triggeredBy: 'Urgency escalation pattern' },
      { agent: 'PaymentGuard', action: 'Flagged UPI payment request as non-standard for insurance premium collection', timestamp: '00:02:10', triggeredBy: 'UPI payment mention' },
      { agent: 'IdentityVerifier', action: 'Caller ID shows mobile number +91 82874 33210 — not linked to any SBI Life employee record', timestamp: '00:02:30', triggeredBy: 'Caller identification check' },
      { agent: 'ScriptDetector', action: 'Identified scripted conversation flow matching known insurance scam template', timestamp: '00:03:00', triggeredBy: 'Script pattern analysis' },
    ],
    evidencePackage: [
      { type: 'call_recording', title: 'Call Recording Analysis', content: 'Full conversation recorded showing high-pressure sales tactics and refusal to provide written documentation. Caller demanded UPI payment to personal ID而非 official channel.' },
      { type: 'number_lookup', title: 'Phone Number Verification', content: 'Number +91 82874 33210 traced to prepaid SIM registered in Noida under fake name. No association with SBI Life Insurance found in corporate directory.' },
      { type: 'threat_assessment', title: 'Scam Pattern Match', content: 'Conversation matches 94% with known "Insurance Lapse" scam pattern documented by TRAI fraud database.' },
    ],
    aiAnalysis: {
      confidence: 89,
      scamProbability: 92,
      threatCategory: 'Insurance Fraud / Voice Phishing',
      deepReasoning: 'The caller creates artificial urgency by claiming immediate policy lapse, then redirects payment to personal UPI instead of official channels. Genuine insurance companies never demand same-day UPI payments. The refusal to provide email confirmation and insistence on immediate payment are classic social engineering tactics.',
      psychologicalTricks: [
        'Artificial urgency — claiming policy expires today',
        'Fear of financial loss — 5 lakh coverage at stake',
        'Authority impersonation — posing as SBI Life agent',
        'Time pressure — preventing victim from verifying independently',
        'Normalizing UPI payment for official premiums',
      ],
      safeActions: [
        'Hang up and call SBI Life Insurance official number 1800-22-9999',
        'Check policy status through official SBI Life app or website',
        'Never share UPI details or make payments based on phone calls',
        'Visit nearest SBI branch to verify policy status',
        'File complaint on National Cybercrime Portal if scammed',
      ],
      victimBehavior: 'Showed initial caution by questioning auto-debit failure. Attempted to request email verification. Could have been pressured by the 6 PM deadline if call continued.',
      preventionAdvice: 'Always verify insurance policy status through official app or branch visit. Never make payments through UPI to individuals. Insurance companies send written notices well before policy lapse.',
      insights: [
        { id: 'urgency', label: 'Urgency Level', value: 'Extreme', score: 95, icon: 'Clock', color: '#DC2626' },
        { id: 'authority', label: 'Authority Claim', value: 'SBI Life Insurance', score: 40, icon: 'Shield', color: '#F59E0B' },
        { id: 'payment', label: 'Payment Pressure', value: 'UPI to Individual', score: 88, icon: 'CreditCard', color: '#DC2626' },
        { id: 'verification', label: 'Verification Block', value: 'Refused Email', score: 82, icon: 'Ban', color: '#EF4444' },
      ],
      recommendations: [
        'Do not make any payment through the provided UPI ID',
        'Call SBI Life Insurance official number to verify policy status',
        'Report the number to TRAI and National Cybercrime Portal',
        'Alert family members about this scam pattern',
      ],
    },
  },
  {
    id: 'atm-card-swap',
    label: 'ATM Card Swap Scam',
    description: 'Scammer approaches victim at an ATM, offers help with a "malfunctioning" machine, and physically swaps the victim\'s debit card with a duplicate while distracting them.',
    transcript: [
      { speaker: 'Scammer', text: 'Bhaiya, machine jam ho gayi hai kya? Mujhe bhi yehi problem aa rahi hai. Mera card bhi atak gaya.' },
      { speaker: 'Victim', text: 'Haan, mujhe bhi withdraw nahi ho raha. Bank wale ko call karta hu.' },
      { speaker: 'Scammer', text: 'Nahi nahi, ek kaam karo. Main SBI ka technician hu. Mujhe card do, main check karke fix kar deta hu. Yeh commonly hota hai.' },
      { speaker: 'Victim', text: 'Theek hai, lekin jaldi karo. Mera 4721 XXXX XXXX 8834 wala card hai.' },
      { speaker: 'Scammer', text: 'Ho gaya! Machine theek hai ab. Aapka card return. Aur haan, next time agar issue aaye toh yeh duplicate card use karna — maine aapke liye backup banaya hai.' },
      { speaker: 'Victim', text: 'Thank you bhaiya. Chalta hu.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 84,
    redFlags: [
      { phrase: 'Mujhe card do', category: 'Requesting card possession', severity: 'CRITICAL' },
      { phrase: 'SBI ka technician hu', category: 'False authority claim', severity: 'HIGH' },
      { phrase: 'Duplicate card banaya hai', category: 'Providing counterfeit card', severity: 'CRITICAL' },
      { phrase: 'Machine theek hai ab', category: 'False resolution claim', severity: 'HIGH' },
      { phrase: 'Next time yeh duplicate card use karna', category: 'Planting malicious instrument', severity: 'CRITICAL' },
    ],
    agentFires: [
      { agent: 'LocationGuard', action: 'ATM location flagged — Sector 18, Noida has 23 reported card swap incidents this month', timestamp: '00:00:30', triggeredBy: 'ATM location context' },
      { agent: 'BehaviorAnalyzer', action: 'Detected impersonation pattern — legitimate bank technicians wear ID cards and never handle customer cards directly', timestamp: '00:01:00', triggeredBy: 'Technician claim without verification' },
      { agent: 'CardValidator', action: 'Flagged duplicate card provision as potential counterfeit — genuine banks do not issue on-the-spot backup cards at ATMs', timestamp: '00:01:30', triggeredBy: 'Duplicate card mention' },
      { agent: 'SocialEngineeringDetector', action: 'Identified distraction-based social engineering — attacker leveraged shared frustration with ATM malfunction', timestamp: '00:02:00', triggeredBy: 'Shared complaint setup pattern' },
      { agent: 'TimelineAnalyzer', action: 'Card swap window estimated at 8-12 seconds during "checking" phase — matches typical swap operation timing', timestamp: '00:02:30', triggeredBy: 'Card possession duration' },
    ],
    evidencePackage: [
      { type: 'atm_footage', title: 'ATM CCTV Footage Request', content: 'CCTV footage from SBI ATM, Sector 18 Noida, Camera 3. Timestamp shows suspect approaching victim at 14:23:15 and departing at 14:27:42. Card swap occurs at approximately 14:25:10.' },
      { type: 'card_analysis', title: 'Duplicate Card Analysis', content: 'The "backup" card provided was a blank white card with cloned magnetic stripe. No chip, no official SBI branding. Confirmed counterfeit upon inspection at branch.' },
    ],
    aiAnalysis: {
      confidence: 93,
      scamProbability: 96,
      threatCategory: 'Physical Card Fraud / ATM Tampering',
      deepReasoning: 'Classic card swap scam where attacker exploits ATM malfunction scenario to gain physical possession of victim\'s card. The "technician" claim is false — bank technicians never handle cards at ATMs. The provided duplicate card is a counterfeit designed to harvest card data. Real bank staff use corporate tools and never create on-the-spot replacements.',
      psychologicalTricks: [
        'Shared frustration — both complaining about same ATM issue',
        'False authority — claiming to be SBI technician',
        'Reciprocity trap — "helping" victim to build trust',
        'Physical proximity — close contact at ATM for card swap',
        'Normalizing the duplicate card as a "backup"',
      ],
      safeActions: [
        'Never hand your card to anyone at an ATM',
        'Call bank helpline number on the back of your card if ATM malfunctions',
        'Check if the person is wearing official bank ID badge',
        'Report suspicious individuals at ATM to bank security',
        'Block card immediately if you suspect a swap occurred',
        'Check account for unauthorized transactions within 24 hours',
      ],
      victimBehavior: 'Trusting behavior — handed card to stranger claiming to be technician without verifying identity. Did not inspect the "duplicate" card before leaving.',
      preventionAdvice: 'Bank employees never ask for your card at ATMs. If an ATM malfunctions, call the helpline printed on the machine or your card. Always inspect any card returned to you.',
      insights: [
        { id: 'physical', label: 'Physical Threat', value: 'Card Swap', score: 98, icon: 'Hand', color: '#DC2626' },
        { id: 'identity', label: 'Identity Verification', value: 'None', score: 10, icon: 'UserX', color: '#DC2626' },
        { id: 'location', label: 'Location Risk', value: 'High Crime Area', score: 75, icon: 'MapPin', color: '#F59E0B' },
        { id: 'timing', label: 'Response Window', value: '4 min exposure', score: 85, icon: 'Timer', color: '#EF4444' },
      ],
      recommendations: [
        'Block your debit card immediately by calling 1800-11-2211',
        'Visit nearest SBI branch to report the incident and get new card',
        'File FIR at local police station with ATM location details',
        'Check account statement for any unauthorized transactions',
        'Request ATM CCTV footage preservation from bank',
      ],
    },
  },
  {
    id: 'social-media-hack',
    label: 'Social Media Account Hack',
    description: 'Scammer sends a fake Instagram password reset link via WhatsApp, gains access to victim\'s account, and then uses it to scam the victim\'s contacts.',
    transcript: [
      { speaker: 'Scammer (via WhatsApp)', text: 'Hi! Instagram ne mujhe bola hai ki aapka account login karne ki koshish ho rahi hai Mumbai se. Yeh aap the? Agar nahi toh yeh link click karo aur password change karo: https://insta-recovery.in/reset' },
      { speaker: 'Victim', text: 'Nahi main nahi tha! Kya karu abhi?' },
      { speaker: 'Scammer', text: 'Jaldi yeh link click karo aur apna purana password daal do. Link 5 minutes mein expire ho jayega. Phir naya password set kar lena.' },
      { speaker: 'Victim', text: 'Link click kiya... ek OTP aa raha hai. Woh daal du kya?' },
      { speaker: 'Scammer', text: 'Haan haan, OTP daal do. Main verify karke account secure kar dunga tumhara.' },
      { speaker: 'Victim', text: 'OTP daal diya. Ab kya hua?' },
      { speaker: 'Scammer', text: 'Account secure hai ab. Thank you!' },
    ],
    riskLevel: 'MEDIUM',
    finalScore: 66,
    redFlags: [
      { phrase: 'Link click karo', category: 'Phishing link', severity: 'CRITICAL' },
      { phrase: 'OTP daal do', category: 'OTP harvesting', severity: 'CRITICAL' },
      { phrase: '5 minutes mein expire', category: 'False urgency', severity: 'HIGH' },
      { phrase: 'Main verify karke secure kar dunga', category: 'False security assurance', severity: 'HIGH' },
      { phrase: 'insta-recovery.in', category: 'Fake domain', severity: 'HIGH' },
      { phrase: 'Mumbai se login', category: 'Fabricated threat', severity: 'MEDIUM' },
    ],
    agentFires: [
      { agent: 'URLAnalyzer', action: 'Domain insta-recovery.in flagged — not owned by Meta/Instagram. Registered 3 days ago via Namecheap.', timestamp: '00:00:45', triggeredBy: 'Suspicious URL detected' },
      { agent: 'OTPShield', action: 'WARNING: Victim attempting to share OTP — this is a phishing attempt to hijack account', timestamp: '00:01:30', triggeredBy: 'OTP sharing attempt' },
      { agent: 'DomainChecker', action: 'SSL certificate on insta-recovery.in issued by Let\'s Encrypt — not consistent with Meta infrastructure', timestamp: '00:01:00', triggeredBy: 'Domain analysis' },
      { agent: 'PatternMatcher', action: 'Matches "Instagram Account Recovery" scam pattern — 2,340 reports on CyberCrime portal this month', timestamp: '00:02:00', triggeredBy: 'Scam pattern match' },
      { agent: 'ContactProtector', action: 'Post-compromise alert — scammer likely to message victim\'s contacts requesting money', timestamp: '00:02:30', triggeredBy: 'Account compromise simulation' },
    ],
    evidencePackage: [
      { type: 'screenshot', title: 'WhatsApp Message Screenshots', content: 'Screenshots of phishing message containing fake Instagram recovery link. Message sent from +91 99887 65432 claiming to be Instagram security team.' },
      { type: 'domain_report', title: 'Domain WHOIS Report', content: 'insta-recovery.in registered on 2026-07-13 via Namecheap, privacy-protected registration. No connection to Meta Platforms Inc. Server hosted in Netherlands.' },
    ],
    aiAnalysis: {
      confidence: 87,
      scamProbability: 91,
      threatCategory: 'Account Hijacking / Phishing',
      deepReasoning: 'The attacker creates panic about unauthorized login, then directs victim to a phishing page that harvests credentials and OTP. Instagram never sends password reset links via WhatsApp from personal numbers. The OTP requested is the real Instagram login OTP, which gives attacker full account access.',
      psychologicalTricks: [
        'Fear of unauthorized access — "Mumbai se login"',
        'False urgency — 5-minute expiry window',
        'Authority impersonation — posing as Instagram security',
        'Technical confusion — mixing "password reset" with "OTP"',
        'False safety promise — "main secure kar dunga"',
      ],
      safeActions: [
        'Never click links sent via WhatsApp claiming to be from social media platforms',
        'Go directly to instagram.com to check login activity',
        'Never share OTP with anyone — Instagram will never ask for it via third-party',
        'Enable two-factor authentication on all social media accounts',
        'Report the WhatsApp number as spam',
      ],
      victimBehavior: 'Clicked phishing link immediately without verification. Shared OTP without understanding it was the real Instagram login code. Tragically common behavior due to panic.',
      preventionAdvice: 'Legitimate platforms never contact you via WhatsApp or ask for OTPs. Always access accounts through official apps. Enable 2FA with authenticator apps instead of SMS.',
      insights: [
        { id: 'phishing', label: 'Phishing Quality', value: 'Credential + OTP', score: 90, icon: 'Fish', color: '#DC2626' },
        { id: 'urgency', label: 'Urgency Level', value: '5 min window', score: 78, icon: 'Clock', color: '#F59E0B' },
        { id: 'impact', label: 'Impact Scope', value: 'Account + Contacts', score: 72, icon: 'Users', color: '#F59E0B' },
        { id: 'recovery', label: 'Recovery Difficulty', value: 'Moderate', score: 55, icon: 'RefreshCw', color: '#059669' },
      ],
      recommendations: [
        'Immediately change Instagram password from official app',
        'Enable two-factor authentication with authenticator app',
        'Review and revoke all suspicious active sessions',
        'Alert contacts that your account may have been compromised',
        'Report phishing number to WhatsApp and CyberCrime portal',
      ],
    },
  },
  {
    id: 'fake-emi-bounce',
    label: 'EMI Bounce Notification Scam',
    description: 'Scammer sends SMS and calls claiming the victim\'s home loan EMI bounced, threatening CIBIL score damage and legal action unless immediate "bounce charges" are paid.',
    transcript: [
      { speaker: 'SMS', text: 'URGENT: Your HDFC Home Loan EMI of 18,750 for July 2026 has bounced. CIBIL score will be impacted in 24 hours. Pay bounce charges of 2,499 immediately: https://hdfc-bouncesettlement.in/pay' },
      { speaker: 'Scammer (call)', text: 'Good morning, this is Priya Mehta from HDFC Bank Loan Recovery Department. Your home loan EMI number HFL-2019-88432 has bounced today. We need to process bounce charges of 2,499 rupees immediately or your CIBIL score will drop by 100 points.' },
      { speaker: 'Victim', text: 'But I have auto-debit set up. It should have been deducted.' },
      { speaker: 'Scammer', text: 'Sir, auto-debit was rejected due to new RBI mandate on high-value transactions. You need to pay bounce charges first, then we can reprocess the EMI. Payment karo UPI se — main link bhej rahi hu.' },
      { speaker: 'Victim', text: 'Bounce charges itne zyada kyun hain? Mere loan agreement mein toh 500 rupay tha.' },
      { speaker: 'Scammer', text: 'Sir, RBI ne charges revise kiye hain April se. Yeh naye hain. Jaldi karo, system update ho raha hai 12 baje.' },
    ],
    riskLevel: 'MEDIUM',
    finalScore: 62,
    redFlags: [
      { phrase: 'CIBIL score impacted in 24 hours', category: 'Credit score threat', severity: 'HIGH' },
      { phrase: 'Bounce charges of 2,499', category: 'Inflated charges', severity: 'MEDIUM' },
      { phrase: 'RBI mandate on high-value transactions', category: 'False regulatory claim', severity: 'HIGH' },
      { phrase: 'hdfc-bouncesettlement.in', category: 'Fake domain', severity: 'CRITICAL' },
      { phrase: 'Payment karo UPI se', category: 'Unofficial payment channel', severity: 'HIGH' },
      { phrase: 'RBI ne charges revise kiye hain', category: 'Fabricated policy change', severity: 'MEDIUM' },
    ],
    agentFires: [
      { agent: 'DomainVerifier', action: 'hdfc-bouncesettlement.in is not an official HDFC domain. Registered 5 days ago. Flagged as phishing.', timestamp: '00:00:30', triggeredBy: 'URL in SMS' },
      { agent: 'LoanVerifier', action: 'HDFC loan number HFL-2019-88432 format does not match HDFC home loan numbering convention', timestamp: '00:01:00', triggeredBy: 'Loan number format check' },
      { agent: 'CallerIDAnalyzer', action: 'Caller number +91 78291 55678 not registered in HDFC Bank corporate directory', timestamp: '00:01:15', triggeredBy: 'Caller verification' },
      { agent: 'RBIPolicyChecker', action: 'No RBI mandate exists regarding EMI bounce charge revision in April 2026 — claim is fabricated', timestamp: '00:01:45', triggeredBy: 'RBI claim verification' },
      { agent: 'CIBILGuard', action: 'CIBIL score cannot drop by 100 points from single EMI bounce — claim is exaggerated', timestamp: '00:02:00', triggeredBy: 'Credit score claim analysis' },
    ],
    evidencePackage: [
      { type: 'sms_record', title: 'SMS Record Analysis', content: 'SMS received from +91 98765 43210 at 09:14 AM. Message contains link to hdfc-bouncesettlement.in. Sent via bulk SMS gateway, not HDFC official channel.' },
      { type: 'call_log', title: 'Call Recording', content: 'Scammer identifying as Priya Mehta called from +91 78291 55678. Background noise suggests call center environment. Used loan number that does not exist in HDFC records.' },
    ],
    aiAnalysis: {
      confidence: 84,
      scamProbability: 88,
      threatCategory: 'Financial Fraud / Loan Scam',
      deepReasoning: 'The scam combines fear of CIBIL damage with fabricated regulatory claims to pressure payment. Genuine banks send multiple notices before any CIBIL impact. The bounce charges quoted (2,499) are significantly higher than actual HDFC charges (typically 500). The fake domain mimics HDFC branding to appear legitimate.',
      psychologicalTricks: [
        'CIBIL fear — threatening credit score damage',
        'Fabricated urgency — 24-hour impact window',
        'Regulatory authority — falsely citing RBI mandates',
        'Technical complexity — blaming "new mandate" for auto-debit failure',
        'Charge inflation — 2,499 vs actual 500',
      ],
      safeActions: [
        'Check HDFC loan account through official net banking or app',
        'Never click links in SMS about loan defaults',
        'Call official HDFC customer care 1800-266-4332 to verify',
        'Check CIBIL score directly through official CIBIL website',
        'Report suspicious SMS to bank and TRAI',
      ],
      victimBehavior: 'Showed good skepticism by questioning the inflated bounce charges. The victim\'s knowledge of original agreement terms provided a partial defense. Could have been pressured by CIBIL threat.',
      preventionAdvice: 'Banks never demand immediate UPI payment for bounce charges. Always verify through official net banking. CIBIL impact from single bounce takes 30+ days, not 24 hours.',
      insights: [
        { id: 'urgency', label: 'Urgency Level', value: '24-hour threat', score: 80, icon: 'Clock', color: '#F59E0B' },
        { id: 'financial', label: 'Financial Amount', value: '2,499 INR', score: 45, icon: 'IndianRupee', color: '#F59E0B' },
        { id: 'authority', label: 'Authority Claim', value: 'HDFC + RBI', score: 35, icon: 'Shield', color: '#059669' },
        { id: 'impact', label: 'Credit Impact', value: 'Exaggerated', score: 70, icon: 'TrendingDown', color: '#EF4444' },
      ],
      recommendations: [
        'Check HDFC loan account status through official net banking',
        'Never click SMS links for loan-related issues',
        'Call HDFC customer care to verify any EMI issues',
        'Report the phishing SMS to TRAI at 1909',
        'Monitor CIBIL score through official channels only',
      ],
    },
  },
  {
    id: 'airline-refund',
    label: 'Fake Airline Refund Scam',
    description: 'Scammer impersonates IndiGo customer support, claiming the victim\'s flight was cancelled and offering immediate refund if bank details are provided.',
    transcript: [
      { speaker: 'Scammer', text: 'Hello, this is Ankit from IndiGo Airlines customer support. I am calling about your booking 6E-4478291 for Mumbai to Delhi on July 20th. The flight has been cancelled due to technical reasons. We are offering full refund of 6,840 rupees.' },
      { speaker: 'Victim', text: 'Oh no, I need to reach Delhi that day. Can you rebook me?' },
      { speaker: 'Scammer', text: 'Sir, we can rebook but refund will take 15 business days. However, if you want immediate refund, we can process it now through UPI. Just share your bank account UPI ID and we will transfer within 5 minutes.' },
      { speaker: 'Victim', text: 'Actually, can you check if there are other flights?' },
      { speaker: 'Scammer', text: 'Sir, I can see one more flight at 6 PM but seats are limited. For immediate refund, share your UPI ID — I will process it and you can book the new flight. Your refund amount is guaranteed.' },
    ],
    riskLevel: 'MEDIUM',
    finalScore: 59,
    redFlags: [
      { phrase: 'Share your UPI ID', category: 'Requesting financial details', severity: 'CRITICAL' },
      { phrase: 'Immediate refund through UPI', category: 'Unusual refund method', severity: 'HIGH' },
      { phrase: 'Seats are limited', category: 'Scarcity pressure', severity: 'MEDIUM' },
      { phrase: 'Refund within 5 minutes', category: 'False speed promise', severity: 'HIGH' },
      { phrase: '6E-4478291', category: 'Unverifiable booking reference', severity: 'MEDIUM' },
    ],
    agentFires: [
      { agent: 'FlightVerifier', action: 'Booking 6E-4478291 not found in IndiGo booking system — reference appears fabricated', timestamp: '00:00:40', triggeredBy: 'Booking reference check' },
      { agent: 'CallerIDAnalyzer', action: 'Caller number +91 91234 56789 not associated with IndiGo customer support', timestamp: '00:01:00', triggeredBy: 'Caller identification' },
      { agent: 'RefundPolicyChecker', action: 'IndiGo does not process refunds via UPI — refunds go to original payment method only', timestamp: '00:01:20', triggeredBy: 'Refund method check' },
      { agent: 'ScarcityDetector', action: 'Detected artificial scarcity tactic — "seats are limited" used to pressure quick decision', timestamp: '00:01:45', triggeredBy: 'Scarcity language' },
    ],
    evidencePackage: [
      { type: 'call_recording', title: 'Call Recording', content: 'Scammer impersonating IndiGo support called from prepaid number. Claimed flight cancellation and offered UPI refund — contradicting official IndiGo refund policy.' },
      { type: 'booking_check', title: 'Booking Verification', content: 'IndiGo confirmed booking 6E-4478291 does not exist in their system. Flight 6E-714 on July 20th Mumbai-Delhi is operating normally.' },
    ],
    aiAnalysis: {
      confidence: 82,
      scamProbability: 85,
      threatCategory: 'Travel Fraud / Refund Scam',
      deepReasoning: 'Legitimate airlines never ask for UPI IDs for refunds — refunds are processed to the original payment method. The fabricated booking number and false flight cancellation are designed to create urgency. The scammer attempts to extract UPI details which could be used for unauthorized debits.',
      psychologicalTricks: [
        'Disruption fear — flight cancellation disrupting travel plans',
        'Immediate solution — promising instant refund',
        'Scarcity pressure — limited seats on alternative flight',
        'Technical authority — citing "technical reasons" for cancellation',
        'Choice overload — presenting refund vs rebooking simultaneously',
      ],
      safeActions: [
        'Check flight status through official IndiGo app or website',
        'Never share UPI ID or bank details over phone',
        'Call official IndiGo support 0124-6173838 to verify',
        'Book or modify flights only through official channels',
        'Report scam calls to airline and CyberCrime portal',
      ],
      victimBehavior: 'Showed reasonable caution by asking about alternative flights instead of immediately sharing UPI details. Could have been pressured by the 5-minute refund promise.',
      preventionAdvice: 'Airlines process refunds to original payment method, never via UPI. Always verify flight status through official app before responding to any cancellation call.',
      insights: [
        { id: 'refund', label: 'Refund Claim', value: '6,840 INR', score: 55, icon: 'IndianRupee', color: '#F59E0B' },
        { id: 'urgency', label: 'Urgency Level', value: 'Same-day', score: 70, icon: 'Clock', color: '#F59E0B' },
        { id: 'verification', label: 'Booking Verified', value: 'Not Found', score: 90, icon: 'XCircle', color: '#DC2626' },
        { id: 'method', label: 'Refund Method', value: 'UPI (Invalid)', score: 88, icon: 'Ban', color: '#EF4444' },
      ],
      recommendations: [
        'Check flight status through official IndiGo app only',
        'Never share UPI ID or bank details for "refunds"',
        'Call IndiGo official number to verify any cancellation',
        'Report the scam number to IndiGo and CyberCrime portal',
        'Alert travel companions about the scam attempt',
      ],
    },
  },
  {
    id: 'student-scholarship',
    label: 'Student Scholarship Scam',
    description: 'Scammer sends SMS claiming the student has been selected for a PM Scholarship Scheme and requests Aadhaar and bank details for "direct benefit transfer."',
    transcript: [
      { speaker: 'SMS', text: 'Congratulations! You have been selected for PM Vidya Scholarship 2026. Amount: 75,000/year. Submit Aadhaar and bank details within 48 hours to receive DBT: https://scholarship-gov.in/claim' },
      { speaker: 'Scammer (call)', text: 'Namaste, I am calling from the Ministry of Education scholarship cell. Your application for PM Vidya Scholarship has been approved. I need to verify your Aadhaar number and bank account for DBT transfer.' },
      { speaker: 'Victim', text: 'I never applied for any scholarship. How was I selected?' },
      { speaker: 'Scammer', text: 'Sir, your details were auto-selected from your 10th board marks. This is a merit-based selection. But you must verify within 48 hours or the amount goes to the next candidate.' },
      { speaker: 'Victim', text: 'Can you send me an official government email?' },
      { speaker: 'Scammer', text: 'Sir, government scholarships don\'t work through email. Only through this verified portal. Share your Aadhaar last 4 digits and bank IFSC code so I can process the transfer.' },
    ],
    riskLevel: 'MEDIUM',
    finalScore: 57,
    redFlags: [
      { phrase: 'scholarship-gov.in', category: 'Fake government domain', severity: 'CRITICAL' },
      { phrase: 'Aadhaar last 4 digits', category: 'Identity harvesting', severity: 'HIGH' },
      { phrase: '48 hours or amount goes to next candidate', category: 'Artificial deadline', severity: 'HIGH' },
      { phrase: 'Auto-selected from board marks', category: 'Unsolicited selection claim', severity: 'MEDIUM' },
      { phrase: 'Government scholarships don\'t work through email', category: 'Preventing verification', severity: 'HIGH' },
      { phrase: 'Share bank IFSC code', category: 'Financial detail harvesting', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'GovernmentDomainChecker', action: 'scholarship-gov.in is not a registered government domain. Official portal is scholarships.gov.in', timestamp: '00:00:30', triggeredBy: 'Domain verification' },
      { agent: 'ScholarshipVerifier', action: 'No PM Vidya Scholarship scheme exists under this name in Ministry of Education records', timestamp: '00:01:00', triggeredBy: 'Scheme name check' },
      { agent: 'AadhaarGuard', action: 'WARNING: Request for Aadhaar details — potential identity theft in progress', timestamp: '00:01:30', triggeredBy: 'Aadhaar detail request' },
      { agent: 'DeadlineDetector', action: '48-hour deadline identified as artificial urgency tactic — government scholarships have 30-60 day windows', timestamp: '00:01:45', triggeredBy: 'Deadline analysis' },
    ],
    evidencePackage: [
      { type: 'sms_record', title: 'SMS Evidence', content: 'SMS received from +91 87654 32109 containing fake government scholarship claim and phishing link to scholarship-gov.in.' },
      { type: 'domain_report', title: 'Domain Analysis', content: 'scholarship-gov.in registered 2 days ago. Not a .gov.in domain. Hosted on commercial server in Singapore.' },
    ],
    aiAnalysis: {
      confidence: 80,
      scamProbability: 84,
      threatCategory: 'Identity Theft / Government Impersonation',
      deepReasoning: 'The scammer impersonates government officials to harvest Aadhaar and bank details. The fake domain mimics official government portals. No genuine scholarship program selects students without application or sends unsolicited calls. The 48-hour deadline prevents independent verification.',
      psychologicalTricks: [
        'Greed appeal — 75,000/year scholarship offer',
        'Authority impersonation — Ministry of Education',
        'Scarcity pressure — 48-hour deadline',
        'Merit flattery — "auto-selected from marks"',
        'Technical dismissal — preventing email verification',
      ],
      safeActions: [
        'Check scholarships.gov.in for legitimate scholarship listings',
        'Never share Aadhaar or bank details over phone',
        'Verify any scholarship through school/college administration',
        'Report phishing SMS to CyberCrime portal',
        'Remember: government never calls for DBT verification',
      ],
      victimBehavior: 'Showed good skepticism by questioning unsolicited selection and requesting email verification. The scammer\'s dismissal of email should have been a major red flag.',
      preventionAdvice: 'Government scholarships require formal application. Never share Aadhaar or bank details via phone. Verify through official scholarships.gov.in portal.',
      insights: [
        { id: 'government', label: 'Gov Impersonation', value: 'Ministry of Education', score: 85, icon: 'Building', color: '#DC2626' },
        { id: 'identity', label: 'Data Requested', value: 'Aadhaar + Bank', score: 92, icon: 'Fingerprint', color: '#EF4444' },
        { id: 'urgency', label: 'Deadline', value: '48 hours', score: 75, icon: 'Clock', color: '#F59E0B' },
        { id: 'financial', label: 'Bait Amount', value: '75,000/year', score: 60, icon: 'IndianRupee', color: '#F59E0B' },
      ],
      recommendations: [
        'Do not share any personal or financial details',
        'Visit official scholarships.gov.in to verify',
        'Report the number to CyberCrime portal immediately',
        'Alert school/college administration about the scam',
        'Never click links in unsolicited scholarship messages',
      ],
    },
  },
  {
    id: 'parcel-customs',
    label: 'International Parcel Customs Scam',
    description: 'Scammer sends parcel delivery notification claiming an international package is held at customs and demands "clearance fee" to release it.',
    transcript: [
      { speaker: 'WhatsApp', text: 'Your international parcel from Amazon UK (Tracking: UK-IN-884421) is held at Mumbai Customs. Clearance fee of 3,850 required. Pay within 24 hours or parcel will be destroyed: https://customs-clearance.in/pay' },
      { speaker: 'Scammer (call)', text: 'Hello, this is Officer Sharma from Mumbai Customs Department. Your parcel tracking UK-IN-884421 contains electronic items valued at 45,000 rupees. We need customs duty clearance fee of 3,850 to release it. Without payment, it will be seized under Section 111 of Customs Act.' },
      { speaker: 'Victim', text: 'I did order something from Amazon UK. What is in the parcel?' },
      { speaker: 'Scammer', text: 'Sir, I cannot disclose contents. But it shows electronics. Pay the 3,850 fee via the link I sent on WhatsApp and your parcel will be delivered tomorrow.' },
      { speaker: 'Victim', text: 'Can I come to the customs office to pay?' },
      { speaker: 'Scammer', text: 'No sir, due to new digital India policy, all payments must be online. Physical visits are not allowed. Pay through the link immediately.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 73,
    redFlags: [
      { phrase: 'customs-clearance.in', category: 'Fake government domain', severity: 'CRITICAL' },
      { phrase: 'Pay within 24 hours or parcel destroyed', category: 'Destruction threat', severity: 'HIGH' },
      { phrase: 'Physical visits not allowed', category: 'Preventing in-person verification', severity: 'HIGH' },
      { phrase: 'Cannot disclose contents', category: 'Avoiding specifics', severity: 'MEDIUM' },
      { phrase: 'Section 111 of Customs Act', category: 'Legal intimidation', severity: 'MEDIUM' },
      { phrase: 'Pay via WhatsApp link', category: 'Unofficial payment channel', severity: 'CRITICAL' },
    ],
    agentFires: [
      { agent: 'GovernmentDomainChecker', action: 'customs-clearance.in is not an official Indian Customs domain. Customs uses icegate.gov.in', timestamp: '00:00:30', triggeredBy: 'Domain verification' },
      { agent: 'TrackingVerifier', action: 'Tracking number UK-IN-884421 does not exist in any known courier or customs database', timestamp: '00:01:00', triggeredBy: 'Tracking number check' },
      { agent: 'CallerIDAnalyzer', action: 'Caller number +91 98765 12345 not registered with Customs Department', timestamp: '00:01:15', triggeredBy: 'Caller verification' },
      { agent: 'LegalClaimChecker', action: 'Section 111 reference is real but misapplied — actual customs clearance does not work this way', timestamp: '00:01:45', triggeredBy: 'Legal claim analysis' },
      { agent: 'PaymentChannelGuard', action: 'Official customs duties are paid at port of entry or through ICEGATE portal, never via WhatsApp links', timestamp: '00:02:00', triggeredBy: 'Payment method analysis' },
    ],
    evidencePackage: [
      { type: 'message_record', title: 'WhatsApp Message', content: 'Message from +91 98765 12345 claiming to be Mumbai Customs. Contains fake tracking number and phishing link to customs-clearance.in.' },
      { type: 'domain_report', title: 'Domain Analysis', content: 'customs-clearance.in registered 4 days ago. Not associated with Government of India. Hosted on commercial cloud infrastructure.' },
    ],
    aiAnalysis: {
      confidence: 86,
      scamProbability: 90,
      threatCategory: 'Package Delivery Fraud / Government Impersonation',
      deepReasoning: 'The scammer exploits the common scenario of international package deliveries to demand fake customs fees. Official customs clearance happens through ICEGATE portal or at physical customs offices. The "parcel destroyed" threat creates urgency while the refusal to allow in-person payment prevents verification.',
      psychologicalTricks: [
        'Package anticipation — victim did order from Amazon UK',
        'Destruction threat — parcel will be destroyed',
        'Legal authority — citing Customs Act Section 111',
        'Digital mandate — "new digital India policy"',
        'Time pressure — 24-hour deadline',
      ],
      safeActions: [
        'Check actual parcel status through Amazon UK tracking',
        'Visit Mumbai Customs office directly if concerned',
        'Never pay customs fees via WhatsApp links',
        'Call official Customs helpline 1800-11-0031',
        'Report phishing message to CyberCrime portal',
      ],
      victimBehavior: 'Showed good instinct by asking to visit customs office in person. The scammer\'s refusal to allow physical payment is a major red flag that should have ended the conversation.',
      preventionAdvice: 'Customs duties are paid at ports or through official ICEGATE portal. Never pay via links received on WhatsApp. Always verify parcel tracking through the original sender.',
      insights: [
        { id: 'government', label: 'Gov Impersonation', value: 'Mumbai Customs', score: 82, icon: 'Building', color: '#DC2626' },
        { id: 'physical', label: 'In-Person Blocked', value: 'Yes', score: 88, icon: 'Ban', color: '#EF4444' },
        { id: 'threat', label: 'Destruction Threat', value: '24 hours', score: 80, icon: 'AlertTriangle', color: '#F59E0B' },
        { id: 'payment', label: 'Payment Channel', value: 'WhatsApp Link', score: 95, icon: 'Link', color: '#DC2626' },
      ],
      recommendations: [
        'Do not click the WhatsApp payment link',
        'Check parcel status through Amazon UK directly',
        'Visit Mumbai Customs office if parcel exists',
        'Report the number to CyberCrime and Customs helpline',
        'Alert family about this common parcel scam pattern',
      ],
    },
  },
  {
    id: 'whatsapp-group-scam',
    label: 'WhatsApp Group Investment Scam',
    description: 'Scammer adds victim to a WhatsApp "Stock Tips" group where fake members share artificially inflated profits, luring victim into a pump-and-dump scheme.',
    transcript: [
      { speaker: 'Group Member 1 (Scammer)', text: 'Just booked 45,000 profit on Vodafone Idea! The tip from Rajesh ji was spot on. Next target is 3I Infotech — entering at 42 rupees!' },
      { speaker: 'Group Member 2 (Scammer)', text: 'Amazing returns! I made 1.2 lakh in just 3 days following the group picks. Rajesh ji is truly a SEBI registered analyst.' },
      { speaker: 'Rajesh (Scammer)', text: 'Welcome new members! I am Rajesh Kapoor, SEBI registered research analyst. For premium picks, transfer 9,999 to my UPI. Guaranteed 30% monthly returns.' },
      { speaker: 'Group Member 3 (Scammer)', text: 'I paid the premium fee last month and already recovered 3x! Best investment ever. Payment karo — limited spots available!' },
      { speaker: 'Victim', text: 'Sounds interesting. Let me think about it.' },
      { speaker: 'Rajesh (Scammer)', text: 'Sir, the next pick drops tomorrow morning at 9:15 AM. Pay 9,999 now to get early entry. Last month\'s members made 2 lakh minimum.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 87,
    redFlags: [
      { phrase: 'Guaranteed 30% monthly returns', category: 'Unrealistic return promise', severity: 'CRITICAL' },
      { phrase: 'SEBI registered research analyst', category: 'False credential claim', severity: 'HIGH' },
      { phrase: 'Pay 9,999 to my UPI', category: 'Payment to individual', severity: 'CRITICAL' },
      { phrase: 'Limited spots available', category: 'Artificial scarcity', severity: 'HIGH' },
      { phrase: 'Made 2 lakh minimum', category: 'Fabricated success stories', severity: 'HIGH' },
      { phrase: 'Next pick drops tomorrow', category: 'Urgency and exclusivity', severity: 'MEDIUM' },
      { phrase: 'Multiple fake testimonials', category: 'Social proof manipulation', severity: 'CRITICAL' },
    ],
    agentFires: [
      { agent: 'SEBIVerifier', action: 'Rajesh Kapoor not found in SEBI registered analyst database. SEBI registration numbers are public — none provided.', timestamp: '00:00:45', triggeredBy: 'SEBI claim check' },
      { agent: 'ReturnAnalyzer', action: '30% monthly guaranteed returns flagged — SEBI prohibits guaranteed return promises. Actual market average is 12-15% annually.', timestamp: '00:01:00', triggeredBy: 'Return claim analysis' },
      { agent: 'GroupBehaviorAnalyzer', action: 'Detected coordinated fake testimonials — 3 members joined within 24 hours with identical message patterns', timestamp: '00:01:30', triggeredBy: 'Group member analysis' },
      { agent: 'PumpDumpDetector', action: '3I Infotech flagged — micro-cap stock with low liquidity, commonly used in pump-and-dump schemes', timestamp: '00:02:00', triggeredBy: 'Stock recommendation analysis' },
      { agent: 'PaymentGuard', action: 'UPI payment to individual for investment advice violates SEBI regulations — investment advisory requires proper licensing', timestamp: '00:02:30', triggeredBy: 'Payment channel analysis' },
    ],
    evidencePackage: [
      { type: 'group_analysis', title: 'WhatsApp Group Analysis', content: 'Group "Stock Market Gains VIP" has 128 members but only 5 accounts are active with testimonials. All active accounts created in last 30 days. Admin "Rajesh Kapoor" account created 15 days ago.' },
      { type: 'sebi_check', title: 'SEBI Database Search', content: 'No registered research analyst named Rajesh Kapoor found in SEBI database. No SEBI registration number provided despite claims of being registered.' },
      { type: 'stock_analysis', title: 'Stock Recommendation Analysis', content: '3I Infotech is a penny stock with average daily volume of 50,000 shares — easily manipulated. Stock has been used in 12 reported pump-and-dump schemes in 2025.' },
    ],
    aiAnalysis: {
      confidence: 95,
      scamProbability: 97,
      threatCategory: 'Investment Fraud / Pump-and-Dump',
      deepReasoning: 'Classic pump-and-dump scheme using WhatsApp group dynamics. Multiple fake accounts create social proof through fabricated testimonials. The "SEBI registered" claim is false — no registration number provided. 30% monthly guaranteed returns violate SEBI regulations. The 9,999 fee is the real scam — the stock picks are worthless or designed to benefit the scammer\'s positions.',
      psychologicalTricks: [
        'Social proof — multiple fake success stories',
        'Authority claim — false SEBI registration',
        'Greed appeal — 30% monthly guaranteed returns',
        'Scarcity — limited spots, next pick tomorrow',
        'FOMO — last month\'s members made 2 lakh',
        'Reciprocity — sharing "free" tips before asking for money',
      ],
      safeActions: [
        'Leave the WhatsApp group immediately',
        'Verify any SEBI registration at sebi.gov.in',
        'Never pay for stock tips through UPI to individuals',
        'Report the group to SEBI and CyberCrime portal',
        'Remember: guaranteed returns do not exist in stock market',
        'Consult a licensed financial advisor for investments',
      ],
      victimBehavior: 'Showed initial hesitation by saying "let me think." Good instinct to not commit immediately. The scammer escalated urgency with "next pick drops tomorrow" to prevent independent verification.',
      preventionAdvice: 'SEBI prohibits guaranteed return promises. Never pay for stock tips through personal UPI. Verify advisor credentials on SEBI website. Legitimate advisors never operate through WhatsApp groups.',
      insights: [
        { id: 'returns', label: 'Return Claim', value: '30% monthly', score: 98, icon: 'TrendingUp', color: '#DC2626' },
        { id: 'social', label: 'Social Proof', value: 'Fake testimonials', score: 95, icon: 'Users', color: '#EF4444' },
        { id: 'credential', label: 'Credential Check', value: 'Not SEBI registered', score: 10, icon: 'ShieldX', color: '#DC2626' },
        { id: 'scheme', label: 'Scheme Type', value: 'Pump-and-Dump', score: 96, icon: 'AlertTriangle', color: '#DC2626' },
      ],
      recommendations: [
        'Leave the WhatsApp group immediately',
        'Do not pay any fee for stock tips',
        'Report the group admin to SEBI at sec.gov.in',
        'File complaint on CyberCrime portal',
        'Warn others who may have been added to the group',
        'Consult SEBI-registered investment advisor for genuine advice',
      ],
    },
  },
  {
    id: 'fake-visa',
    label: 'Fake Visa Processing Scam',
    description: 'Scammer poses as a VFS Global agent, claiming the victim\'s UK visa is approved but requires "processing completion fee" for stamping.',
    transcript: [
      { speaker: 'Scammer', text: 'Hello, this is calling from VFS Global Delhi. Your UK tourist visa application VFS-2026-UK-44781 has been approved by the British High Commission. Congratulations! But the visa stamping is pending — you need to pay a completion fee of 8,500 within 48 hours.' },
      { speaker: 'Victim', text: 'Really? I applied 3 weeks ago. That is great news! But I thought VFS fees were already paid.' },
      { speaker: 'Scammer', text: 'Sir, the initial fees covered processing. This is a separate stamping fee introduced last month. It is mandatory. Without payment, the approval will be cancelled and you will need to reapply.' },
      { speaker: 'Victim', text: 'Can I come to the VFS center to pay?' },
      { speaker: 'Scammer', text: 'Sir, due to the new system, stamping fees can only be paid online. I am sending you a payment link. Pay within 48 hours or your visa approval expires.' },
      { speaker: 'Victim', text: 'Let me check my email for the approval first.' },
      { speaker: 'Scammer', text: 'The email will come after payment is processed. Please pay first — this is how the new system works.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 80,
    redFlags: [
      { phrase: 'Completion fee of 8,500', category: 'Fake additional fee', severity: 'CRITICAL' },
      { phrase: '48 hours or approval cancelled', category: 'Artificial deadline', severity: 'HIGH' },
      { phrase: 'Only be paid online', category: 'Preventing in-person verification', severity: 'HIGH' },
      { phrase: 'Email will come after payment', category: 'Reverse verification order', severity: 'CRITICAL' },
      { phrase: 'New system', category: 'Fabricated policy change', severity: 'MEDIUM' },
      { phrase: 'Approval expires', category: 'Threat of cancellation', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VFSGlobalVerifier', action: 'VFS Global does not collect additional fees after application submission. All fees are paid at time of application.', timestamp: '00:00:40', triggeredBy: 'Fee claim check' },
      { agent: 'CallerIDAnalyzer', action: 'Caller number +91 98765 43210 not associated with VFS Global or British High Commission', timestamp: '00:01:00', triggeredBy: 'Caller verification' },
      { agent: 'VisaProcessChecker', action: 'UK visa approval emails are sent before stamping — not after payment. Process described is reversed.', timestamp: '00:01:30', triggeredBy: 'Process sequence analysis' },
      { agent: 'PolicyChangeChecker', action: 'No new stamping fee policy introduced by VFS Global or UK visa authorities in 2026', timestamp: '00:01:45', triggeredBy: 'Policy claim verification' },
    ],
    evidencePackage: [
      { type: 'call_recording', title: 'Call Recording', content: 'Scammer impersonating VFS Global called from prepaid number. Claimed visa approval and demanded 8,500 stamping fee via online payment only.' },
      { type: 'vfs_verification', title: 'VFS Global Statement', content: 'VFS Global confirms no additional fees are collected after application submission. All fees are paid during initial appointment. "Stamping fee" does not exist.' },
    ],
    aiAnalysis: {
      confidence: 88,
      scamProbability: 91,
      threatCategory: 'Immigration Fraud / Visa Scam',
      deepReasoning: 'The scammer exploits the anxiety of visa processing to demand fake fees. VFS Global collects all fees at the time of application — there is no separate "stamping fee." The claim that email comes after payment reverses the legitimate process. The 48-hour deadline prevents victims from independently verifying with VFS.',
      psychologicalTricks: [
        'Excitement exploitation — visa approval creates positive emotion',
        'Authority impersonation — VFS Global agent',
        'Fear of loss — approval cancellation threat',
        'Technical excuse — "new system" for online-only payment',
        'Process reversal — pay first, get email later',
      ],
      safeActions: [
        'Check visa status through official VFS Global portal',
        'Call VFS Global official number 0120-6636000',
        'Never pay additional fees after application submission',
        'Visit VFS center in person if concerned',
        'Report the number to VFS and CyberCrime portal',
      ],
      victimBehavior: 'Good instinct to check email for approval first. The scammer\'s claim that email comes after payment is a critical red flag that should have ended the conversation.',
      preventionAdvice: 'VFS Global collects all fees at time of application. No additional fees are ever requested. Always verify through official VFS portal or visit the center in person.',
      insights: [
        { id: 'fee', label: 'Fake Fee', value: '8,500 INR', score: 70, icon: 'IndianRupee', color: '#F59E0B' },
        { id: 'urgency', label: 'Deadline', value: '48 hours', score: 80, icon: 'Clock', color: '#F59E0B' },
        { id: 'process', label: 'Process Reversal', value: 'Pay before email', score: 95, icon: 'ArrowRight', color: '#DC2626' },
        { id: 'verification', label: 'In-Person Blocked', value: 'Yes', score: 88, icon: 'Ban', color: '#EF4444' },
      ],
      recommendations: [
        'Check visa status through official VFS Global portal',
        'Do not pay any additional fees after application',
        'Call VFS Global official helpline to verify',
        'Visit VFS center in person if concerned',
        'Report the scam call to CyberCrime portal',
      ],
    },
  },
  {
    id: 'electricity-meter',
    label: 'Electricity Meter Replacement Scam',
    description: 'Scammer calls posing as BSES Delhi engineer, claiming the victim\'s electricity meter needs urgent replacement and demanding 2,500 for "smart meter upgrade."',
    transcript: [
      { speaker: 'Scammer', text: 'Hello, this is Ramesh from BSES Rajdhani Power. Your electricity meter at the registered address needs immediate replacement. We are upgrading all meters to smart meters under government scheme. The upgrade fee is 2,500 rupees.' },
      { speaker: 'Victim', text: 'I didn\'t receive any notice about this. Is it mandatory?' },
      { speaker: 'Scammer', text: 'Sir, it was sent to your registered mobile but maybe you missed it. The deadline is this Friday. If not replaced, your connection will be disconnected on Monday.' },
      { speaker: 'Victim', text: 'I will visit the BSES office to pay and schedule.' },
      { speaker: 'Scammer', text: 'Sir, BSES offices don\'t handle meter replacements anymore. It is all online now. Pay the 2,500 fee and our technician will come tomorrow to install.' },
    ],
    riskLevel: 'LOW',
    finalScore: 35,
    redFlags: [
      { phrase: 'Disconnection on Monday', category: 'Service disconnection threat', severity: 'MEDIUM' },
      { phrase: 'Pay online only', category: 'Preventing in-person verification', severity: 'MEDIUM' },
      { phrase: 'Maybe you missed it', category: 'Dismissive of verification', severity: 'LOW' },
      { phrase: '2,500 upgrade fee', category: 'Unexpected charge', severity: 'MEDIUM' },
    ],
    agentFires: [
      { agent: 'BSESVerifier', action: 'BSES Delhi has not announced mandatory smart meter upgrade requiring payment from consumers', timestamp: '00:00:30', triggeredBy: 'BSES policy check' },
      { agent: 'CallerIDAnalyzer', action: 'Caller number +91 91122 33445 not registered with BSES Rajdhani Power', timestamp: '00:01:00', triggeredBy: 'Caller verification' },
      { agent: 'DeadlineAnalyzer', action: 'Monday disconnection threat flagged — BSES requires 15-day notice before disconnection', timestamp: '00:01:30', triggeredBy: 'Disconnection claim check' },
    ],
    evidencePackage: [
      { type: 'call_recording', title: 'Call Recording', content: 'Scammer claiming to be BSES engineer demanded 2,500 for meter upgrade. Caller ID showed prepaid mobile number.' },
    ],
    aiAnalysis: {
      confidence: 72,
      scamProbability: 70,
      threatCategory: 'Utility Fraud / Meter Scam',
      deepReasoning: 'The scammer exploits the government smart meter rollout to demand fake upgrade fees. BSES Delhi does not charge consumers for meter upgrades under the government scheme. The disconnection threat and refusal to allow in-person payment are classic scam indicators. The lower score reflects the relatively smaller amount and less sophisticated approach.',
      psychologicalTricks: [
        'Government scheme reference — leveraging legitimate policy',
        'Disconnection fear — threatening basic utility service',
        'Normalizing payment — "it is all online now"',
        'Technical excuse — dismissing in-person option',
      ],
      safeActions: [
        'Check BSES account through official app or website',
        'Call BSES official number 1800-345-2273',
        'Visit nearest BSES office to verify',
        'Never pay for meter upgrades through phone calls',
        'Report the number to BSES and CyberCrime portal',
      ],
      victimBehavior: 'Showed reasonable instinct by wanting to visit BSES office. The scammer\'s dismissal of physical offices was a red flag. The victim did not fall for the scam.',
      preventionAdvice: 'BSES meter upgrades under government schemes are free for consumers. Never pay upgrade fees over phone. Always verify through official BSES channels.',
      insights: [
        { id: 'amount', label: 'Amount Requested', value: '2,500 INR', score: 30, icon: 'IndianRupee', color: '#059669' },
        { id: 'urgency', label: 'Deadline', value: 'This Friday', score: 55, icon: 'Clock', color: '#F59E0B' },
        { id: 'service', label: 'Service Threat', value: 'Disconnection', score: 65, icon: 'Zap', color: '#F59E0B' },
        { id: 'verification', label: 'Verification Blocked', value: 'Online only', score: 50, icon: 'Ban', color: '#F59E0B' },
      ],
      recommendations: [
        'Check BSES account status through official app',
        'Call BSES helpline to verify any meter upgrade notice',
        'Visit BSES office if concerned',
        'Report the scam call to BSES customer care',
        'Remember: government smart meter upgrades are free',
      ],
    },
  },
  {
    id: 'bank-merge-scam',
    label: 'Bank Merger Data Update Scam',
    description: 'Scammer sends SMS claiming the victim\'s Union Bank account needs urgent data migration due to bank merger, requiring Aadhaar and PAN verification.',
    transcript: [
      { speaker: 'SMS', text: 'IMPORTANT: Union Bank of India merger with Andhra Bank is complete. Update your KYC data within 7 days or account will be frozen. Click: https://unionbank-merger.in/kyc' },
      { speaker: 'Scammer (call)', text: 'Hello, this is Deepak from Union Bank of India customer care. Your account needs urgent KYC update due to the merger. Without update, your account will be frozen on July 22nd. Please share your Aadhaar number and PAN for verification.' },
      { speaker: 'Victim', text: 'My account is already KYC updated. Why do I need to do it again?' },
      { speaker: 'Scammer', text: 'Sir, merger requires fresh KYC in new system. This is a one-time process. Share your Aadhaar last 6 digits and PAN, I will update it now.' },
      { speaker: 'Victim', text: 'Can I do this through net banking?' },
      { speaker: 'Scammer', text: 'No sir, merger update can only be done through our verification call. Net banking won\'t work for this. Please share details now.' },
    ],
    riskLevel: 'MEDIUM',
    finalScore: 64,
    redFlags: [
      { phrase: 'unionbank-merger.in', category: 'Fake domain', severity: 'CRITICAL' },
      { phrase: 'Account will be frozen', category: 'Account freeze threat', severity: 'HIGH' },
      { phrase: 'Share Aadhaar and PAN', category: 'Identity harvesting', severity: 'CRITICAL' },
      { phrase: 'Net banking won\'t work', category: 'Preventing self-service verification', severity: 'HIGH' },
      { phrase: 'Fresh KYC in new system', category: 'Fabricated merger requirement', severity: 'MEDIUM' },
      { phrase: '7 days or frozen', category: 'Artificial deadline', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'DomainVerifier', action: 'unionbank-merger.in is not an official Union Bank domain. Bank uses unionbankofindia.co.in', timestamp: '00:00:30', triggeredBy: 'Domain verification' },
      { agent: 'MergerStatusChecker', action: 'Union Bank-Andhra Bank merger completed in 2020. No new KYC update required in 2026', timestamp: '00:01:00', triggeredBy: 'Merger timeline check' },
      { agent: 'CallerIDAnalyzer', action: 'Caller number +91 98765 54321 not registered with Union Bank of India', timestamp: '00:01:15', triggeredBy: 'Caller verification' },
      { agent: 'KYCProcessChecker', action: 'Bank never calls for KYC updates. KYC is done through branch visit or official app only', timestamp: '00:01:45', triggeredBy: 'KYC process check' },
    ],
    evidencePackage: [
      { type: 'sms_record', title: 'SMS Evidence', content: 'SMS from +91 87654 32110 containing fake merger KYC update link. Sent via bulk SMS gateway.' },
      { type: 'domain_report', title: 'Domain Analysis', content: 'unionbank-merger.in registered 6 days ago. Not a .bank.in domain. No connection to Union Bank of India.' },
    ],
    aiAnalysis: {
      confidence: 83,
      scamProbability: 86,
      threatCategory: 'Banking Fraud / Identity Theft',
      deepReasoning: 'The scammer exploits the completed Union Bank-Andhra Bank merger to demand fake KYC updates. The merger was completed in 2020 and no additional KYC is required. The fake domain mimics the bank\'s branding. Banks never call for KYC updates — this is always done through branches or official apps.',
      psychologicalTricks: [
        'Institutional authority — Union Bank official claim',
        'Account freeze fear — threatening basic banking access',
        'Merger complexity — exploiting genuine event confusion',
        'Technical restriction — "net banking won\'t work"',
        'One-time framing — making it seem simple and necessary',
      ],
      safeActions: [
        'Check Union Bank account through official net banking',
        'Call Union Bank official number 1800-22-2244',
        'Visit nearest Union Bank branch for any KYC concerns',
        'Never share Aadhaar or PAN over phone',
        'Report the SMS to bank and CyberCrime portal',
      ],
      victimBehavior: 'Good skepticism by questioning the need for re-KYC and suggesting net banking. The scammer\'s dismissal of net banking was a clear red flag.',
      preventionAdvice: 'Bank mergers do not require fresh KYC from customers. Never share Aadhaar or PAN over phone. Banks handle such updates through official channels.',
      insights: [
        { id: 'identity', label: 'Data Requested', value: 'Aadhaar + PAN', score: 90, icon: 'Fingerprint', color: '#DC2626' },
        { id: 'threat', label: 'Account Threat', value: 'Freeze in 7 days', score: 75, icon: 'Lock', color: '#F59E0B' },
        { id: 'merger', label: 'Merger Status', value: 'Completed 2020', score: 10, icon: 'Calendar', color: '#059669' },
        { id: 'method', label: 'KYC Method', value: 'Phone (Invalid)', score: 85, icon: 'Phone', color: '#EF4444' },
      ],
      recommendations: [
        'Check Union Bank account through official net banking',
        'Never share Aadhaar or PAN over phone',
        'Visit Union Bank branch for any KYC concerns',
        'Report the scam number to bank and CyberCrime',
        'Remember: bank mergers do not require customer KYC updates',
      ],
    },
  },
  {
    id: 'tech-support-popup',
    label: 'Tech Support Popup Scam',
    description: 'Victim sees a browser popup claiming "Windows Security Alert" with a fake Microsoft helpline number. Calling the number leads to remote access scam.',
    transcript: [
      { speaker: 'Popup', text: 'WINDOWS SECURITY ALERT: Your computer has been infected with 5 viruses! Your personal data is at risk. Call Microsoft Support immediately at 1800-XXX-XXXX. Do not shut down your computer.' },
      { speaker: 'Scammer', text: 'Thank you for calling Microsoft Support. I can see your computer has multiple security threats. Your Windows license has also expired. I need remote access to fix this immediately.' },
      { speaker: 'Victim', text: 'I just bought this laptop 6 months ago. How can the license be expired?' },
      { speaker: 'Scammer', text: 'Sir, due to the security breach, your license was deactivated for protection. I need to access your computer remotely to restore it. Please go to anydesk.com and download the remote access tool.' },
      { speaker: 'Victim', text: 'Can I take it to a local repair shop instead?' },
      { speaker: 'Scammer', text: 'Sir, if you take it outside, your warranty will be voided. Only Microsoft support can fix this. The infection is spreading to your bank data. Please download AnyDesk now.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 71,
    redFlags: [
      { phrase: '5 viruses detected', category: 'Fake virus alert', severity: 'CRITICAL' },
      { phrase: 'Download AnyDesk', category: 'Remote access tool request', severity: 'CRITICAL' },
      { phrase: 'Warranty will be voided', category: 'False warranty threat', severity: 'HIGH' },
      { phrase: 'License deactivated for protection', category: 'Fabricated technical claim', severity: 'HIGH' },
      { phrase: 'Spreading to bank data', category: 'Financial fear escalation', severity: 'HIGH' },
      { phrase: 'Do not shut down', category: 'Preventing independent resolution', severity: 'MEDIUM' },
    ],
    agentFires: [
      { agent: 'PopupDetector', action: 'Browser popup identified as fake Microsoft alert — Microsoft never displays such popups or provides phone numbers', timestamp: '00:00:20', triggeredBy: 'Popup content analysis' },
      { agent: 'RemoteAccessGuard', action: 'CRITICAL: AnyDesk request detected — remote access tool will give scammer full computer control', timestamp: '00:01:00', triggeredBy: 'AnyDesk mention' },
      { agent: 'TechnicalClaimChecker', action: 'Windows license cannot be deactivated due to virus infection — claim is technically impossible', timestamp: '00:01:30', triggeredBy: 'License claim analysis' },
      { agent: 'WarrantyChecker', action: 'Third-party repair does not void manufacturer warranty — warranty claim is false', timestamp: '00:02:00', triggeredBy: 'Warranty threat analysis' },
    ],
    evidencePackage: [
      { type: 'screenshot', title: 'Browser Popup Screenshot', content: 'Fake Windows Security Alert popup appeared while browsing. Contains fake Microsoft helpline number 1800-XXX-XXXX and urgent language to prevent user from closing the browser.' },
      { type: 'technical_analysis', title: 'Technical Analysis', content: 'Windows Defender never displays phone numbers in security alerts. AnyDesk is a legitimate remote access tool being weaponized by scammers for unauthorized computer access.' },
    ],
    aiAnalysis: {
      confidence: 91,
      scamProbability: 94,
      threatCategory: 'Tech Support Fraud / Remote Access Scam',
      deepReasoning: 'Classic tech support scam starting with fake browser popup. The scammer escalates from "virus infection" to "license deactivation" to "bank data breach" to pressure the victim. AnyDesk request is the critical moment — once installed, the scammer gains full control of the computer and can access banking, personal files, and install malware.',
      psychologicalTricks: [
        'Fear of data loss — "personal data at risk"',
        'Technical authority — Microsoft Support impersonation',
        'Urgency escalation — virus spreading to bank data',
        'Warranty threat — preventing local repair',
        'Exclusive solution — "only Microsoft can fix"',
      ],
      safeActions: [
        'Close the browser popup immediately — it cannot harm your computer if not interacted with',
        'Never call numbers displayed in browser popups',
        'Never download remote access tools at someone\'s request',
        'Run Windows Defender scan if concerned',
        'Visit official Microsoft support website if needed',
        'Clear browser cache and consider running antivirus scan',
      ],
      victimBehavior: 'Showed good instinct by suggesting local repair shop. The scammer\'s warranty threat was designed to counter this. Did not download AnyDesk — scam was not successful.',
      preventionAdvice: 'Microsoft never displays phone numbers in security popups. Close any such popup. Never give remote access to your computer. Legitimate tech support never cold-calls.',
      insights: [
        { id: 'remote', label: 'Remote Access', value: 'AnyDesk requested', score: 98, icon: 'Monitor', color: '#DC2626' },
        { id: 'fear', label: 'Fear Level', value: 'Virus + Bank data', score: 85, icon: 'AlertTriangle', color: '#F59E0B' },
        { id: 'authority', label: 'Authority Claim', value: 'Microsoft Support', score: 30, icon: 'Building', color: '#059669' },
        { id: 'technical', label: 'Technical Claims', value: 'All false', score: 95, icon: 'XCircle', color: '#EF4444' },
      ],
      recommendations: [
        'Close the browser popup immediately',
        'Never download AnyDesk or remote access tools for unsolicited calls',
        'Run Windows Defender full scan',
        'Clear browser cache and cookies',
        'Report the helpline number to CyberCrime portal',
        'If AnyDesk was installed, uninstall immediately and change all passwords',
      ],
    },
  },
];
