import type { TranscriptScenario } from './types';

export const SCENARIO_BATCH_1: TranscriptScenario[] = [
  {
    id: 'upi-fraud',
    label: 'UPI Fraud — Fake Merchant',
    description: 'Scammer posing as merchant demands UPI refund to fraudulent account',
    transcript: [
      { speaker: 'SCAMMER', text: 'Namaste, I am calling from Paytm merchant support. Your recent payment of Rs 4,999 to Sharma Electronics was debited twice due to a server error.' },
      { speaker: 'SCAMMER', text: 'I can see the double debit in our system. To process an immediate refund, I need your UPI ID and the OTP that was just sent to your phone.' },
      { speaker: 'SCAMMER', text: 'The refund will be processed within 5 minutes. If you do not cooperate, the amount will not be refunded and you will lose Rs 9,998 total.' },
      { speaker: 'VICTIM', text: 'But I only made one payment. How can it be debited twice?' },
      { speaker: 'SCAMMER', text: 'Sir, this is a known glitch in the UPI system. Many customers are affected today. I am trying to help you recover your money. Please share the OTP quickly before the system locks the refund.' },
    ],
    riskLevel: 'CRITICAL',
    finalScore: 94,
    redFlags: [
      { phrase: 'UPI ID and the OTP', category: 'Credential Harvesting', severity: 'CRITICAL' },
      { phrase: 'server error', category: 'False Urgency', severity: 'HIGH' },
      { phrase: 'double debit', category: 'Fabricated Problem', severity: 'HIGH' },
      { phrase: 'share the OTP', category: 'OTP Harvesting', severity: 'CRITICAL' },
      { phrase: 'system locks the refund', category: 'Artificial Pressure', severity: 'HIGH' },
      { phrase: 'many customers are affected', category: 'Social Proof Manipulation', severity: 'MEDIUM' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller ID does not match any Paytm support number — flagged as spoofed VoIP', timestamp: '00:00:01', triggeredBy: 'Unverified caller ID' },
      { agent: 'NLP Intent Agent', action: 'Detected refund scam pattern — opening with fabricated financial problem', timestamp: '00:00:03', triggeredBy: '"debited twice due to server error"' },
      { agent: 'Credential Request Agent', action: 'ALERT: OTP requested — outside legitimate refund protocol', timestamp: '00:00:05', triggeredBy: '"share the OTP"' },
      { agent: 'Financial Flow Agent', action: 'UPI refund never requires OTP sharing — protocol violation detected', timestamp: '00:00:06', triggeredBy: 'Refund + OTP combination' },
      { agent: 'Urgency Detector Agent', action: 'Time pressure applied — "5 minutes" deadline with loss threat', timestamp: '00:00:07', triggeredBy: '"within 5 minutes"' },
      { agent: 'Evidence Compiler', action: 'Generated fraud alert package — CRITICAL risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'UPI Refund Scam Alert', content: 'CRITICAL: Caller impersonating Paytm merchant support requesting OTP for fake double-debit refund. Legitimate UPI refunds never require OTP sharing. This is a known scam pattern targeting UPI users.' },
      { type: 'FINANCIAL', title: 'Financial Flow Analysis', content: 'UPI refund requests are processed automatically by the bank without any OTP from the customer. The request for OTP indicates credential harvesting for unauthorized transactions.' },
    ],
    aiAnalysis: {
      confidence: 95.2,
      scamProbability: 96.8,
      threatCategory: 'UPI Refund Scam',
      deepReasoning: 'This transcript shows a classic UPI refund scam where the scammer fabricates a double-debit problem and requests OTP under the guise of processing a refund. Legitimate UPI refunds are processed automatically without any customer OTP.',
      psychologicalTricks: [
        'Creating a fabricated financial loss to trigger panic',
        'Offering a quick solution to exploit urgency',
        'Requesting OTP disguised as refund processing',
        'Using "many customers affected" to normalize the scam',
      ],
      safeActions: [
        'Hang up immediately — do not share any OTP',
        'Check your actual bank statement for any double debit',
        'Report the call to Paytm at 0120-4455966',
        'File a complaint at cybercrime.gov.in',
      ],
      victimBehavior: 'Victims share OTP believing it is for refund processing. Scammers use the OTP to authorize fraudulent UPI transactions. Average loss: Rs 15,000-50,000.',
      preventionAdvice: 'No UPI platform ever asks for OTP to process refunds. Refunds are automatic. Always check your bank statement directly rather than trusting phone calls.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Refund Scam', score: 95, icon: 'shield', color: '#f43f5e' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'High', score: 82, icon: 'brain', color: '#f97316' },
        { id: 'urgency', label: 'Urgency Detection', value: 'High', score: 85, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Paytm Support', score: 88, icon: 'eye', color: '#f43f5e' },
        { id: 'financial', label: 'Financial Threat', value: 'OTP Harvesting', score: 96, icon: 'shield', color: '#f43f5e' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'OTP Access', score: 94, icon: 'lock', color: '#f43f5e' },
      ],
      recommendations: [
        'Hang up immediately — do not share OTP under any circumstances',
        'Check your bank statement for actual double debits',
        'Report to Paytm official helpline 0120-4455966',
        'File complaint at cybercrime.gov.in',
        'Enable UPI transaction limits for additional safety',
      ],
    },
  },
  {
    id: 'qr-code-scam',
    label: 'QR Code Scanner Fraud',
    description: 'Scammer sends QR code that debits instead of credits the victim',
    transcript: [
      { speaker: 'SCAMMER', text: 'Hello, I am your Flipkart delivery partner. I have your package but the system shows payment pending. Can you scan this QR code to confirm delivery?' },
      { speaker: 'SCAMMER', text: 'It is just a verification QR code. It will not charge you anything. I need to close the delivery in my app.' },
      { speaker: 'VICTIM', text: 'I already paid online. Why do I need to scan a QR code?' },
      { speaker: 'SCAMMER', text: 'Sir, the online payment did not reflect in our system due to network issue. Please scan quickly — I have 15 more deliveries to make and this is holding up the whole route.' },
      { speaker: 'SCAMMER', text: 'If you do not scan, I will have to return the package to the warehouse and you will need to re-order. The refund process takes 7-10 days.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 78,
    redFlags: [
      { phrase: 'scan this QR code', category: 'QR Code Fraud', severity: 'CRITICAL' },
      { phrase: 'will not charge you', category: 'False Reassurance', severity: 'HIGH' },
      { phrase: 'payment did not reflect', category: 'Fabricated Problem', severity: 'HIGH' },
      { phrase: 'return the package to warehouse', category: 'Coercion Threat', severity: 'MEDIUM' },
      { phrase: '15 more deliveries', category: 'Artificial Pressure', severity: 'MEDIUM' },
      { phrase: 'refund process takes 7-10 days', category: 'Loss Aversion Manipulation', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller claims delivery partner but no verified delivery app integration detected', timestamp: '00:00:01', triggeredBy: 'Unverified delivery claim' },
      { agent: 'NLP Intent Agent', action: 'QR code payment redirect pattern detected — customer would send money instead of receiving', timestamp: '00:00:03', triggeredBy: '"scan this QR code"' },
      { agent: 'Credential Request Agent', action: 'QR code scanned in pay mode would authorize outgoing payment', timestamp: '00:00:05', triggeredBy: 'Payment QR pattern' },
      { agent: 'Urgency Detector Agent', action: 'Time pressure via "15 deliveries" and return-to-warehouse threat', timestamp: '00:00:06', triggeredBy: '"holding up the whole route"' },
      { agent: 'Policy Compliance Agent', action: 'Flipkart never requires QR scan for delivery confirmation — policy violation', timestamp: '00:00:07', triggeredBy: 'Delivery protocol check' },
      { agent: 'Evidence Compiler', action: 'Generated QR scam alert — HIGH risk', timestamp: '00:00:08', triggeredBy: 'Multiple flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'QR Code Payment Scam Alert', content: 'HIGH: Delivery partner impersonator requesting QR code scan for "verification." Scanned QR would authorize outgoing payment, not confirm delivery. Flipkart does not use QR codes for delivery confirmation.' },
    ],
    aiAnalysis: {
      confidence: 88.5,
      scamProbability: 82.3,
      threatCategory: 'QR Code Payment Redirect',
      deepReasoning: 'The scammer uses a fake delivery scenario to get the victim to scan a QR code. In UPI, scanning a QR code in pay mode authorizes a payment FROM the scanner TO the payee. The scammer frames it as "verification" but it would actually transfer money.',
      psychologicalTricks: [
        'Authority impersonation as delivery partner',
        'False reassurance that QR code will not charge',
        'Creating urgency with 15 pending deliveries',
        'Threatening return-to-warehouse to exploit loss aversion',
      ],
      safeActions: [
        'Do not scan any QR code presented by strangers',
        'Check your Flipkart app directly for order status',
        'Contact Flipkart customer support at 1800-202-9898',
        'If you already scanned, check your bank statement immediately',
      ],
      victimBehavior: 'Victims scan the QR code believing it is for verification. The QR code in pay mode authorizes a payment from the victim to the scammer. Average loss: Rs 2,000-10,000.',
      preventionAdvice: 'QR codes in UPI pay mode authorize outgoing payments. Never scan QR codes from unknown persons for "verification." Legitimate deliveries do not require QR scans.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'QR Redirect', score: 85, icon: 'shield', color: '#f97316' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Moderate', score: 65, icon: 'brain', color: '#eab308' },
        { id: 'urgency', label: 'Urgency Detection', value: 'Moderate', score: 72, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Delivery Partner', score: 78, icon: 'eye', color: '#f97316' },
        { id: 'financial', label: 'Financial Threat', value: 'QR Payment', score: 88, icon: 'shield', color: '#f43f5e' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Payment Access', score: 82, icon: 'lock', color: '#f97316' },
      ],
      recommendations: [
        'Never scan QR codes from unknown persons — they authorize payments',
        'Check your Flipkart app directly for order and payment status',
        'Contact Flipkart support at 1800-202-9898',
        'Report the incident at cybercrime.gov.in',
      ],
    },
  },
  {
    id: 'job-offer-scam',
    label: 'Fake Job Offer — Advance Fee',
    description: 'Employment scam demanding upfront registration and training fees',
    transcript: [
      { speaker: 'SCAMMER', text: 'Congratulations! You have been selected for the Data Entry Operator position at Wipro Technologies. Your resume was shortlisted from our HR database.' },
      { speaker: 'SCAMMER', text: 'The salary is Rs 35,000 per month with full benefits. But before we can issue your appointment letter, you need to complete a mandatory registration process.' },
      { speaker: 'SCAMMER', text: 'The registration fee is Rs 2,500 and the training materials fee is Rs 1,500. Total Rs 4,000 needs to be paid today to confirm your position.' },
      { speaker: 'VICTIM', text: 'I did not apply to Wipro. How did you get my resume?' },
      { speaker: 'SCAMMER', text: 'Your resume was uploaded to our job portal by a recruitment agency. Many companies access this database. This is a limited-time offer — 5 positions left.' },
      { speaker: 'SCAMMER', text: 'If you do not pay today, the position will be given to the next candidate. We cannot hold it beyond today.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 82,
    redFlags: [
      { phrase: 'registration fee', category: 'Advance Fee Fraud', severity: 'CRITICAL' },
      { phrase: 'training materials fee', category: 'Advance Fee Fraud', severity: 'CRITICAL' },
      { phrase: 'paid today', category: 'Artificial Urgency', severity: 'HIGH' },
      { phrase: '5 positions left', category: 'Scarcity Tactic', severity: 'HIGH' },
      { phrase: 'limited-time offer', category: 'Pressure Tactic', severity: 'HIGH' },
      { phrase: 'position will be given to next candidate', category: 'FOMO Manipulation', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller ID shows mobile number — not a corporate line', timestamp: '00:00:01', triggeredBy: 'Non-corporate caller ID' },
      { agent: 'NLP Intent Agent', action: 'Advance fee pattern detected — requesting upfront payment for job', timestamp: '00:00:03', triggeredBy: '"registration fee" + "training materials fee"' },
      { agent: 'Financial Flow Agent', action: 'Legitimate employers never charge fees — classic advance fee fraud', timestamp: '00:00:05', triggeredBy: 'Fee demand pattern' },
      { agent: 'Urgency Detector Agent', action: 'Scarcity and urgency combined — "5 positions" and "today only"', timestamp: '00:00:06', triggeredBy: '"5 positions left"' },
      { agent: 'Policy Compliance Agent', action: 'Wipro official policy: no recruitment fees charged — verified against public statements', timestamp: '00:00:07', triggeredBy: 'Policy violation check' },
      { agent: 'Evidence Compiler', action: 'Generated advance fee fraud alert — HIGH risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'Employment Fraud Alert', content: 'HIGH: Fake job offer from "Wipro Technologies" demanding Rs 4,000 registration and training fees. Legitimate companies never charge recruitment fees. This is a classic advance fee employment scam.' },
    ],
    aiAnalysis: {
      confidence: 91.3,
      scamProbability: 89.7,
      threatCategory: 'Advance Fee Employment Fraud',
      deepReasoning: 'The scammer impersonates a major IT company (Wipro) and offers a job with attractive salary, then demands upfront fees for registration and training. Legitimate employers never charge candidates. The urgency and scarcity tactics pressure victims into paying without verification.',
      psychologicalTricks: [
        'Authority impersonation using a well-known company name',
        'Offering attractive salary to create desire',
        'Demanding small upfront fees that seem reasonable',
        'Using scarcity ("5 positions left") to pressure immediate action',
        'Creating urgency with "today only" deadline',
      ],
      safeActions: [
        'Do not pay any fees — legitimate employers never charge',
        'Verify the offer directly on Wipro careers page',
        'Report to Wipro HR at their official contact',
        'File complaint at cybercrime.gov.in',
        'Warn others about this scam on social media',
      ],
      victimBehavior: 'Victims pay the fee hoping for the job, then receive fake appointment letters requesting more fees. Average loss: Rs 5,000-25,000 before realizing.',
      preventionAdvice: 'No legitimate company charges recruitment fees. Always verify job offers through official company websites and career portals.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Advance Fee', score: 90, icon: 'shield', color: '#f43f5e' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'High', score: 85, icon: 'brain', color: '#f97316' },
        { id: 'urgency', label: 'Urgency Detection', value: 'High', score: 88, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Wipro HR', score: 82, icon: 'eye', color: '#f97316' },
        { id: 'financial', label: 'Financial Threat', value: 'Rs 4,000 Fee', score: 75, icon: 'shield', color: '#f97316' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Low', score: 30, icon: 'lock', color: '#10b981' },
      ],
      recommendations: [
        'Do not pay any registration or training fees',
        'Verify the offer on Wipro official careers page',
        'Report to cybercrime.gov.in',
        'Check Naukri/LinkedIn for legitimate Wipro openings',
      ],
    },
  },
  {
    id: 'whatsapp-phishing',
    label: 'WhatsApp Phishing Link',
    description: 'Malicious link sent via WhatsApp claiming to be from a known contact',
    transcript: [
      { speaker: 'SCAMMER', text: 'Hey, is this your photo? 😂 someone sent me this link of you' },
      { speaker: 'SCAMMER', text: 'www.freecharge-secure.in/verify?id=884721' },
      { speaker: 'VICTIM', text: 'What photo? I did not send anything.' },
      { speaker: 'SCAMMER', text: 'Click the link and see for yourself. It is a Google Photos link. Your face is clearly visible. Everyone in the group has seen it already.' },
      { speaker: 'SCAMMER', text: 'Hurry up and check before more people see it. You can report it and get it removed if you verify your identity through the link.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 85,
    redFlags: [
      { phrase: 'Click the link', category: 'Phishing Link', severity: 'CRITICAL' },
      { phrase: 'verify your identity', category: 'Credential Harvesting', severity: 'CRITICAL' },
      { phrase: 'everyone in the group has seen it', category: 'Social Pressure', severity: 'HIGH' },
      { phrase: 'hurry up', category: 'Artificial Urgency', severity: 'HIGH' },
      { phrase: 'report it and get it removed', category: 'False Solution', severity: 'HIGH' },
      { phrase: 'freecharge-secure.in', category: 'Spoofed Domain', severity: 'CRITICAL' },
    ],
    agentFires: [
      { agent: 'URL Analysis Agent', action: 'Flagged suspicious URL — freecharge-secure.in is not a legitimate domain', timestamp: '00:00:01', triggeredBy: '"freecharge-secure.in"' },
      { agent: 'NLP Intent Agent', action: 'Social pressure and curiosity bait pattern detected', timestamp: '00:00:03', triggeredBy: '"is this your photo"' },
      { agent: 'Phishing Detector Agent', action: 'Malicious link disguised as identity verification — would harvest credentials', timestamp: '00:00:05', triggeredBy: '"verify your identity through the link"' },
      { agent: 'Urgency Detector Agent', action: 'Social shame pressure combined with time urgency', timestamp: '00:00:06', triggeredBy: '"hurry up and check before more people see it"' },
      { agent: 'Evidence Compiler', action: 'Generated phishing alert — HIGH risk', timestamp: '00:00:07', triggeredBy: 'Multiple flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'WhatsApp Phishing Alert', content: 'HIGH: Suspicious link shared via WhatsApp claiming to show a photo of the victim. The URL freecharge-secure.in is a spoofed domain designed to harvest credentials. Do not click the link.' },
    ],
    aiAnalysis: {
      confidence: 92.1,
      scamProbability: 93.5,
      threatCategory: 'WhatsApp Phishing',
      deepReasoning: 'This is a classic WhatsApp phishing attack using curiosity and social shame to lure victims into clicking a malicious link. The spoofed domain mimics a legitimate payment service. Clicking the link would lead to credential harvesting or malware installation.',
      psychologicalTricks: [
        'Curiosity bait using "is this your photo"',
        'Social shame pressure claiming everyone has seen it',
        'Offering a fake solution ("verify identity to remove")',
        'Creating urgency to prevent rational thinking',
      ],
      safeActions: [
        'Do NOT click the link under any circumstances',
        'Block and report the sender on WhatsApp',
        'Report to cybercrime.gov.in',
        'If you clicked, change all passwords immediately',
        'Run antivirus scan on your device',
      ],
      victimBehavior: 'Victims click the link out of curiosity or shame, leading to credential theft or malware installation. Average loss: varies from data theft to financial loss.',
      preventionAdvice: 'Never click suspicious links from unknown numbers. WhatsApp has a built-in link safety check. If concerned, ask the person directly through a different channel.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Phishing', score: 94, icon: 'shield', color: '#f43f5e' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Very High', score: 92, icon: 'brain', color: '#f43f5e' },
        { id: 'urgency', label: 'Urgency Detection', value: 'High', score: 85, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Known Contact', score: 70, icon: 'eye', color: '#f97316' },
        { id: 'financial', label: 'Financial Threat', value: 'Credential Theft', score: 88, icon: 'shield', color: '#f43f5e' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Critical', score: 95, icon: 'lock', color: '#f43f5e' },
      ],
      recommendations: [
        'Do NOT click the link — it is a phishing attempt',
        'Block and report the sender',
        'Report to cybercrime.gov.in',
        'If clicked, change all passwords immediately',
      ],
    },
  },
  {
    id: 'crypto-investment',
    label: 'Crypto Investment Scam',
    description: 'Fake crypto trading platform promising guaranteed high returns',
    transcript: [
      { speaker: 'SCAMMER', text: 'Hi, I am Priya from CoinGain Pro. You were recommended by a friend for our exclusive crypto investment program.' },
      { speaker: 'SCAMMER', text: 'Our AI trading bot has delivered 340% returns in the last 6 months. We have over 12,000 active investors and SEBI registration.' },
      { speaker: 'SCAMMER', text: 'To get started, you just need to deposit Rs 10,000 minimum. Our bot will trade for you and you can withdraw profits anytime through our secure dashboard.' },
      { speaker: 'VICTIM', text: '340% returns? That sounds too good to be true.' },
      { speaker: 'SCAMMER', text: 'I understand your concern. That is why we offer a 7-day trial with Rs 1,000. You will see the returns in your dashboard. Many of our investors started with just Rs 1,000 and now have lakhs.' },
      { speaker: 'SCAMMER', text: 'But this offer closes at midnight. After that, the minimum deposit goes up to Rs 50,000. You should act now while the opportunity is still available.' },
    ],
    riskLevel: 'CRITICAL',
    finalScore: 91,
    redFlags: [
      { phrase: '340% returns', category: 'Unrealistic Returns', severity: 'CRITICAL' },
      { phrase: 'AI trading bot', category: 'Fake Technology', severity: 'HIGH' },
      { phrase: 'SEBI registration', category: 'False Regulatory Claim', severity: 'HIGH' },
      { phrase: 'closes at midnight', category: 'Artificial Urgency', severity: 'HIGH' },
      { phrase: 'minimum deposit goes up', category: 'Scarcity Tactic', severity: 'HIGH' },
      { phrase: 'many investors started with Rs 1,000', category: 'Social Proof Manipulation', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller not registered with SEBI — unverifiable credentials', timestamp: '00:00:01', triggeredBy: 'Unverified SEBI claim' },
      { agent: 'NLP Intent Agent', action: 'Investment scam pattern detected — unrealistic returns promised', timestamp: '00:00:03', triggeredBy: '"340% returns in 6 months"' },
      { agent: 'Financial Flow Agent', action: 'No legitimate investment guarantees 340% returns — Ponzi indicators present', timestamp: '00:00:05', triggeredBy: 'Guaranteed return claim' },
      { agent: 'Urgency Detector Agent', action: 'Midnight deadline with price increase threat — classic pressure tactic', timestamp: '00:00:07', triggeredBy: '"closes at midnight"' },
      { agent: 'Regulatory Check Agent', action: 'SEBI registration cannot be verified — CoinGain Pro not in registered entities list', timestamp: '00:00:08', triggeredBy: 'SEBI verification failed' },
      { agent: 'Evidence Compiler', action: 'Generated investment fraud alert — CRITICAL risk', timestamp: '00:00:09', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'Investment Fraud Alert', content: 'CRITICAL: Fake crypto investment platform "CoinGain Pro" promising 340% returns. Not SEBI registered. Uses AI trading bot claims and urgency tactics to pressure deposits. Likely Ponzi scheme.' },
    ],
    aiAnalysis: {
      confidence: 94.7,
      scamProbability: 97.2,
      threatCategory: 'Cryptocurrency Investment Fraud',
      deepReasoning: 'This transcript exhibits all hallmarks of a crypto investment scam: unrealistic return promises (340% in 6 months), fake technology claims (AI trading bot), false regulatory compliance (SEBI registration), and classic urgency/scarcity tactics. The "trial with Rs 1,000" is a hook to establish trust before demanding larger deposits.',
      psychologicalTricks: [
        'Unrealistic return promises to trigger greed',
        'Fake technology claims (AI trading bot) to appear sophisticated',
        'False SEBI registration to establish legitimacy',
        'Low entry point (Rs 1,000 trial) to reduce resistance',
        'Midnight deadline to prevent verification',
        'Social proof with "12,000 active investors"',
      ],
      safeActions: [
        'Do not invest any money — this is a scam',
        'Report to SEBI at their investor complaint portal',
        'File complaint at cybercrime.gov.in',
        'Report the WhatsApp number to WhatsApp',
        'Warn friends and family about this scam',
      ],
      victimBehavior: 'Victims start with small amounts, see fake profits on the dashboard, then invest larger sums. When they try to withdraw, they are told to pay "taxes" or "fees." Average loss: Rs 50,000-5,00,000.',
      preventionAdvice: 'No investment can guarantee 340% returns. Always verify SEBI registration on the official SEBI website. Never invest based on WhatsApp messages.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Ponzi/Investment', score: 96, icon: 'shield', color: '#f43f5e' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Extreme', score: 90, icon: 'brain', color: '#f43f5e' },
        { id: 'urgency', label: 'Urgency Detection', value: 'High', score: 88, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Fake SEBI Entity', score: 92, icon: 'eye', color: '#f43f5e' },
        { id: 'financial', label: 'Financial Threat', value: 'Investment Loss', score: 97, icon: 'shield', color: '#f43f5e' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Financial Data', score: 85, icon: 'lock', color: '#f43f5e' },
      ],
      recommendations: [
        'Do NOT invest any money — this is a scam',
        'Report to SEBI investor complaint portal',
        'File complaint at cybercrime.gov.in',
        'Report the WhatsApp number',
      ],
    },
  },
  {
    id: 'emergency-relative',
    label: 'Emergency Relative Scam',
    description: 'Scammer impersonating family member in distress needing urgent money',
    transcript: [
      { speaker: 'SCAMMER', text: 'Bhaiya, it is me Rahul. I am in real trouble. My phone fell in water and I am using a friend\'s phone to call you.' },
      { speaker: 'SCAMMER', text: 'I met with an accident near Pune. The hospital is asking for Rs 25,000 deposit before they can treat me. Mom and dad are not picking up their phones.' },
      { speaker: 'SCAMMER', text: 'Please send the money to this UPI ID immediately — hospitalcare2024@paytm. The doctor says if I do not get treatment in the next hour, my leg might need surgery.' },
      { speaker: 'VICTIM', text: 'Rahul? Which Rahul? This does not sound like my brother.' },
      { speaker: 'SCAMMER', text: 'Bhaiya, I am in pain. Please do not ask questions. Just send the money. I will explain everything later. The hospital staff is getting angry with me.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 80,
    redFlags: [
      { phrase: 'send the money to this UPI ID', category: 'Financial Extraction', severity: 'CRITICAL' },
      { phrase: 'hospitalcare2024@paytm', category: 'Suspicious UPI ID', severity: 'HIGH' },
      { phrase: 'do not ask questions', category: 'Question Suppression', severity: 'HIGH' },
      { phrase: 'phone fell in water', category: 'Excuse for Unknown Number', severity: 'HIGH' },
      { phrase: 'mom and dad are not picking up', category: 'Isolation Tactic', severity: 'HIGH' },
      { phrase: 'next hour', category: 'Artificial Urgency', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Voice does not match known family member patterns — possible impersonation', timestamp: '00:00:01', triggeredBy: 'Voice mismatch detected' },
      { agent: 'NLP Intent Agent', action: 'Emergency money request pattern — classic family impersonation scam', timestamp: '00:00:03', triggeredBy: '"accident" + "hospital" + "send money"' },
      { agent: 'Financial Flow Agent', action: 'Suspicious UPI ID hospitalcare2024@paytm — not associated with any hospital', timestamp: '00:00:05', triggeredBy: '"hospitalcare2024@paytm"' },
      { agent: 'Isolation Pattern Agent', action: 'Isolation tactics: unknown number, "parents not picking up," "do not ask questions"', timestamp: '00:00:06', triggeredBy: 'Multiple isolation indicators' },
      { agent: 'Urgency Detector Agent', action: 'Medical emergency urgency with "next hour" deadline', timestamp: '00:00:07', triggeredBy: '"next hour"' },
      { agent: 'Evidence Compiler', action: 'Generated family impersonation scam alert — HIGH risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'Family Impersonation Scam Alert', content: 'HIGH: Caller impersonating family member claiming medical emergency. Requests money via UPI to suspicious account. Classic emergency scam targeting family members. Verify by calling the person directly on their known number.' },
    ],
    aiAnalysis: {
      confidence: 89.4,
      scamProbability: 87.6,
      threatCategory: 'Family Emergency Impersonation',
      deepReasoning: 'This transcript shows a classic family emergency scam where the scammer impersonates a relative in distress. The use of a generic name ("Rahul"), unknown number, medical emergency urgency, and suspicious UPI ID are all indicators of fraud. The scammer actively suppresses questions to prevent verification.',
      psychologicalTricks: [
        'Exploiting family bond and emotional attachment',
        'Creating medical emergency urgency',
        'Isolating the victim by claiming parents are unavailable',
        'Suppressing questions with "do not ask questions"',
        'Using pain and distress to bypass rational thinking',
      ],
      safeActions: [
        'Do NOT send any money',
        'Try to call your actual family member on their known number',
        'Call other family members to verify the emergency',
        'If you sent money, call 1930 immediately',
        'Report the UPI ID to your bank',
      ],
      victimBehavior: 'Victims send money out of concern for their family member, often without verification. By the time they realize it is a scam, the money is gone. Average loss: Rs 10,000-50,000.',
      preventionAdvice: 'Always verify emergencies by calling the person directly on their known number. Ask a question only the real person would know. No hospital demands UPI payment over phone.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Family Impersonation', score: 88, icon: 'shield', color: '#f43f5e' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Extreme', score: 95, icon: 'brain', color: '#f43f5e' },
        { id: 'urgency', label: 'Urgency Detection', value: 'High', score: 85, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Family Member', score: 82, icon: 'eye', color: '#f97316' },
        { id: 'financial', label: 'Financial Threat', value: 'Rs 25,000 UPI', score: 80, icon: 'shield', color: '#f97316' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Low', score: 20, icon: 'lock', color: '#10b981' },
      ],
      recommendations: [
        'Do NOT send money — verify by calling the person directly',
        'Ask a question only your real family member would know',
        'Call other family members to cross-check',
        'If you sent money, call 1930 immediately',
      ],
    },
  },
  {
    id: 'kyc-update-scam',
    label: 'Fake KYC Update Call',
    description: 'Scammer impersonating bank demanding KYC update with personal details',
    transcript: [
      { speaker: 'SCAMMER', text: 'This is SBI Customer Care. Your KYC for account ending in 4521 has expired. As per RBI mandate, your account will be frozen within 48 hours if not updated.' },
      { speaker: 'SCAMMER', text: 'I can update your KYC right now over the phone. I need your full name, date of birth, Aadhaar number, and the OTP sent to your registered mobile.' },
      { speaker: 'SCAMMER', text: 'This is a one-time process. Once done, your account will be active for the next 5 years. Many customers are facing account freezes today because of this.' },
      { speaker: 'VICTIM', text: 'I went to the branch last month for KYC. Why would it expire so soon?' },
      { speaker: 'SCAMMER', text: 'Sir, there was a system update and all KYCs done in the last 6 months need re-verification. This is a new RBI circular. If your account freezes, you cannot use ATM or UPI for 7-10 days until re-verification.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 76,
    redFlags: [
      { phrase: 'account will be frozen', category: 'Threat Induction', severity: 'HIGH' },
      { phrase: 'Aadhaar number and the OTP', category: 'Credential Harvesting', severity: 'CRITICAL' },
      { phrase: 'RBI mandate', category: 'False Authority', severity: 'HIGH' },
      { phrase: 'many customers are facing', category: 'Social Proof', severity: 'MEDIUM' },
      { phrase: 'new RBI circular', category: 'Fabricated Regulation', severity: 'HIGH' },
      { phrase: 'cannot use ATM or UPI', category: 'Loss Threat', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller ID not matching SBI official number — spoofed', timestamp: '00:00:01', triggeredBy: 'Non-SBI caller ID' },
      { agent: 'NLP Intent Agent', action: 'KYC phishing pattern detected — requesting Aadhaar and OTP', timestamp: '00:00:03', triggeredBy: '"Aadhaar number" + "OTP"' },
      { agent: 'Credential Request Agent', action: 'ALERT: Aadhaar number and OTP requested — identity theft risk', timestamp: '00:00:05', triggeredBy: 'Aadhaar + OTP request' },
      { agent: 'Policy Compliance Agent', action: 'SBI never conducts KYC updates over phone — policy violation', timestamp: '00:00:06', triggeredBy: 'KYC over phone protocol' },
      { agent: 'Urgency Detector Agent', action: '48-hour freeze threat combined with 7-10 day inconvenience', timestamp: '00:00:07', triggeredBy: '"frozen within 48 hours"' },
      { agent: 'Evidence Compiler', action: 'Generated KYC phishing alert — HIGH risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'KYC Phishing Alert', content: 'HIGH: Caller impersonating SBI demanding Aadhaar and OTP for fake KYC update. Banks never conduct KYC over phone. This is identity theft. Do not share any details.' },
    ],
    aiAnalysis: {
      confidence: 87.8,
      scamProbability: 84.2,
      threatCategory: 'KYC Phishing',
      deepReasoning: 'The scammer impersonates SBI and creates urgency around KYC expiry, then requests Aadhaar and OTP. This is a classic KYC phishing scam. Banks never conduct KYC updates over phone, and RBI does not mandate phone-based KYC.',
      psychologicalTricks: [
        'False RBI authority to establish legitimacy',
        'Account freeze threat to create urgency',
        'Requesting Aadhaar + OTP for identity theft',
        'Social proof with "many customers facing issues"',
        'Creating inconvenience narrative (7-10 days without banking)',
      ],
      safeActions: [
        'Do not share Aadhaar, OTP, or any personal details',
        'Hang up and call SBI official number 1800-11-2211',
        'Visit your SBI branch for any KYC concerns',
        'Check your account status through SBI app',
        'Report the call to cybercrime.gov.in',
      ],
      victimBehavior: 'Victims share Aadhaar and OTP, which scammers use to open new accounts or make unauthorized transactions. Average loss: Rs 30,000-2,00,000.',
      preventionAdvice: 'Banks never call for KYC updates. Always visit your branch or use the official bank app for KYC. RBI never mandates phone-based verification.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'KYC Phishing', score: 86, icon: 'shield', color: '#f97316' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Moderate', score: 70, icon: 'brain', color: '#eab308' },
        { id: 'urgency', label: 'Urgency Detection', value: 'High', score: 82, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'SBI Customer Care', score: 78, icon: 'eye', color: '#f97316' },
        { id: 'financial', label: 'Financial Threat', value: 'Identity Theft', score: 90, icon: 'shield', color: '#f43f5e' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Critical', score: 95, icon: 'lock', color: '#f43f5e' },
      ],
      recommendations: [
        'Do NOT share Aadhaar, OTP, or any personal details',
        'Call SBI official helpline 1800-11-2211',
        'Visit your SBI branch for KYC concerns',
        'Report to cybercrime.gov.in',
      ],
    },
  },
  {
    id: 'romance-scam',
    label: 'Romance/Relationship Scam',
    description: 'Online dating scammer building emotional bond then requesting money',
    transcript: [
      { speaker: 'SCAMMER', text: 'Hi dear, I just landed in Mumbai for my business trip. I was so excited to finally meet you in person.' },
      { speaker: 'SCAMMER', text: 'But my bag with all my documents and wallet was stolen at the airport. I have no money for hotel or food. The police are not helping.' },
      { speaker: 'SCAMMER', text: 'Can you please transfer Rs 15,000 to my friend\'s UPI? I will pay you back the moment my replacement card arrives tomorrow. I am so embarrassed to ask.' },
      { speaker: 'VICTIM', text: 'Oh no, that is terrible. Which airport? I can come pick you up.' },
      { speaker: 'SCAMMER', text: 'That is so sweet of you but the police advised me not to move around. Just please send the money — my friend Rohit will collect it. His UPI is rohit.help@okicici.' },
      { speaker: 'SCAMMER', text: 'I feel so alone here. You are the only person I can trust. Please help me. I will make it up to you, I promise.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 88,
    redFlags: [
      { phrase: 'transfer Rs 15,000', category: 'Financial Extraction', severity: 'CRITICAL' },
      { phrase: 'rohit.help@okicici', category: 'Suspicious UPI ID', severity: 'HIGH' },
      { phrase: 'only person I can trust', category: 'Emotional Manipulation', severity: 'HIGH' },
      { phrase: 'police advised me not to move', category: 'Excuse to Avoid Meeting', severity: 'HIGH' },
      { phrase: 'pay you back tomorrow', category: 'False Promise', severity: 'HIGH' },
      { phrase: 'my friend will collect', category: 'Third Party Proxy', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Voice characteristics do not match claimed identity — accent analysis inconclusive', timestamp: '00:00:01', triggeredBy: 'Voice verification failed' },
      { agent: 'NLP Intent Agent', action: 'Romance scam pattern detected — emotional buildup followed by money request', timestamp: '00:00:03', triggeredBy: 'Relationship + money request' },
      { agent: 'Financial Flow Agent', action: 'Suspicious UPI rohit.help@okicici — third party collection indicates fraud', timestamp: '00:00:05', triggeredBy: '"rohit.help@okicici"' },
      { agent: 'Isolation Pattern Agent', action: 'Isolation from meeting in person — "police advised not to move"', timestamp: '00:00:06', triggeredBy: 'Avoidance of in-person verification' },
      { agent: 'Emotional Manipulation Agent', action: 'High emotional manipulation — "only person I can trust" + "feel so alone"', timestamp: '00:00:07', triggeredBy: 'Emotional exploitation detected' },
      { agent: 'Evidence Compiler', action: 'Generated romance scam alert — HIGH risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'Romance Scam Alert', content: 'HIGH: Online dating contact claiming emergency in Mumbai requesting Rs 15,000 via friend\'s UPI. Classic romance scam pattern — emotional buildup followed by financial request. Do not send money.' },
    ],
    aiAnalysis: {
      confidence: 90.5,
      scamProbability: 91.8,
      threatCategory: 'Romance/Relationship Fraud',
      deepReasoning: 'This transcript shows a classic romance scam where the scammer has built an emotional connection over time, then creates an emergency to extract money. The use of a third-party UPI ("friend Rohit"), refusal to meet in person, and heavy emotional manipulation are all red flags.',
      psychologicalTricks: [
        'Emotional dependency built over weeks/months of online interaction',
        'Creating a sympathetic emergency to trigger helping behavior',
        'Using third-party proxy to obscure money trail',
        'Refusing in-person meeting with fake police advice',
        'Emotional pressure: "only person I can trust"',
      ],
      safeActions: [
        'Do NOT send any money',
        'Try to verify the person\'s identity through video call',
        'Ask to meet in person at a public place',
        'If you already sent money, call 1930 immediately',
        'Report the profile on the dating platform',
      ],
      victimBehavior: 'Victims send money out of emotional attachment and concern, often multiple times. Average loss: Rs 25,000-3,00,000 over weeks.',
      preventionAdvice: 'Never send money to someone you have not met in person. Romance scammers build emotional bonds over weeks before requesting money. Verify identity through video calls.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Romance Scam', score: 92, icon: 'shield', color: '#f43f5e' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Extreme', score: 96, icon: 'brain', color: '#f43f5e' },
        { id: 'urgency', label: 'Urgency Detection', value: 'High', score: 80, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Fake Dating Profile', score: 85, icon: 'eye', color: '#f97316' },
        { id: 'financial', label: 'Financial Threat', value: 'Rs 15,000 UPI', score: 82, icon: 'shield', color: '#f97316' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Emotional Data', score: 70, icon: 'lock', color: '#f97316' },
      ],
      recommendations: [
        'Do NOT send money to someone you have not met',
        'Request a video call to verify identity',
        'Ask to meet in person at a public place',
        'If you sent money, call 1930 immediately',
      ],
    },
  },
  {
    id: 'lottery-scam',
    label: 'Lottery/Prize Win Scam',
    description: 'Fake lottery notification claiming the victim has won a large prize',
    transcript: [
      { speaker: 'SCAMMER', text: 'Congratulations! Your mobile number has been selected as the Grand Prize winner in the Amazon Great Indian Festival Lottery. You have won Rs 25,00,000!' },
      { speaker: 'SCAMMER', text: 'To claim your prize, you need to pay a small processing fee of Rs 3,500 and a TDS charge of Rs 25,000. The total Rs 28,500 will be deducted from your prize amount.' },
      { speaker: 'SCAMMER', text: 'We need to verify your identity before transfer. Please share your PAN card number, bank account details, and a photo of your Aadhaar card.' },
      { speaker: 'VICTIM', text: 'I did not enter any lottery. How did my number get selected?' },
      { speaker: 'SCAMMER', text: 'Sir, Amazon automatically enters all registered customers. You are lucky! But this prize expires in 24 hours. After that, it goes to the next winner.' },
    ],
    riskLevel: 'MEDIUM',
    finalScore: 65,
    redFlags: [
      { phrase: 'processing fee', category: 'Advance Fee Fraud', severity: 'HIGH' },
      { phrase: 'TDS charge', category: 'Fake Tax', severity: 'HIGH' },
      { phrase: 'PAN card number and bank details', category: 'Data Harvesting', severity: 'CRITICAL' },
      { phrase: 'did not enter any lottery', category: 'Unsolicited Prize', severity: 'HIGH' },
      { phrase: 'expires in 24 hours', category: 'Artificial Urgency', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller ID shows international number — not Amazon India', timestamp: '00:00:01', triggeredBy: 'International caller ID' },
      { agent: 'NLP Intent Agent', action: 'Lottery scam pattern detected — unsolicited prize with fee demand', timestamp: '00:00:03', triggeredBy: '"won Rs 25,00,000"' },
      { agent: 'Financial Flow Agent', action: 'Advance fee of Rs 28,500 requested — classic lottery scam', timestamp: '00:00:05', triggeredBy: '"processing fee" + "TDS charge"' },
      { agent: 'Credential Request Agent', action: 'ALERT: PAN, bank details, and Aadhaar photo requested — identity theft risk', timestamp: '00:00:06', triggeredBy: 'Identity document harvesting' },
      { agent: 'Urgency Detector Agent', action: '24-hour deadline to claim "prize"', timestamp: '00:00:07', triggeredBy: '"expires in 24 hours"' },
      { agent: 'Evidence Compiler', action: 'Generated lottery scam alert — MEDIUM risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'Lottery Scam Alert', content: 'MEDIUM: Fake Amazon lottery claiming Rs 25 lakh prize. Demands Rs 28,500 in fees and personal documents. Amazon does not conduct lotteries. Do not share any information or pay any fees.' },
    ],
    aiAnalysis: {
      confidence: 86.2,
      scamProbability: 72.4,
      threatCategory: 'Lottery/Prize Fraud',
      deepReasoning: 'This is a classic lottery scam variant. The scammer claims the victim won a large prize but demands fees and personal documents to "claim" it. Amazon does not conduct random lotteries. The advance fee and data harvesting combination makes this a dual-threat scam.',
      psychologicalTricks: [
        'Greed trigger with large prize amount (Rs 25 lakh)',
        'Framing fees as deductions from prize (not additional cost)',
        'Creating urgency with 24-hour expiry',
        'Using well-known brand (Amazon) for legitimacy',
      ],
      safeActions: [
        'Do not pay any fees or share personal documents',
        'Amazon does not conduct lotteries — this is a scam',
        'Report the call to cybercrime.gov.in',
        'Block the number',
      ],
      victimBehavior: 'Victims pay the fee and share documents, leading to both financial loss and identity theft. Average loss: Rs 5,000-30,000 plus identity theft risk.',
      preventionAdvice: 'No company conducts lotteries without your participation. Never pay fees to claim prizes. Legitimate lotteries deduct taxes automatically.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Lottery Scam', score: 72, icon: 'shield', color: '#f97316' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Moderate', score: 60, icon: 'brain', color: '#eab308' },
        { id: 'urgency', label: 'Urgency Detection', value: 'Moderate', score: 65, icon: 'zap', color: '#eab308' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Amazon', score: 68, icon: 'eye', color: '#f97316' },
        { id: 'financial', label: 'Financial Threat', value: 'Rs 28,500 Fee', score: 70, icon: 'shield', color: '#f97316' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'PAN + Aadhaar', score: 88, icon: 'lock', color: '#f43f5e' },
      ],
      recommendations: [
        'Do not pay any fees or share documents',
        'Amazon does not conduct lotteries',
        'Report to cybercrime.gov.in',
        'Block the number',
      ],
    },
  },
  {
    id: 'income-tax-scam',
    label: 'Income Tax Department Fraud',
    description: 'Fake IT officer threatening arrest for tax evasion',
    transcript: [
      { speaker: 'SCAMMER', text: 'This is Officer Vikram Singh from the Income Tax Department, Delhi. Your PAN card has been flagged for tax evasion of Rs 12,50,000 over the last 3 years.' },
      { speaker: 'SCAMMER', text: 'A criminal case has been registered under Section 276C of the Income Tax Act. You are required to cooperate immediately or face arrest.' },
      { speaker: 'SCAMMER', text: 'We have detected undeclared foreign accounts in your name. To verify if these are genuine or fraudulent, we need to access your bank accounts through a secure government portal.' },
      { speaker: 'SCAMMER', text: 'Download the AnyDesk app and share the connection code with me. I will guide you through the verification process. This is mandatory under the new IT Act amendment.' },
      { speaker: 'SCAMMER', text: 'If you do not cooperate within 2 hours, your PAN will be permanently blacklisted and all your bank accounts will be frozen.' },
    ],
    riskLevel: 'CRITICAL',
    finalScore: 92,
    redFlags: [
      { phrase: 'tax evasion of Rs 12,50,000', category: 'Fabricated Allegation', severity: 'CRITICAL' },
      { phrase: 'face arrest', category: 'Fear Induction', severity: 'CRITICAL' },
      { phrase: 'Download the AnyDesk app', category: 'Remote Access Tool', severity: 'CRITICAL' },
      { phrase: 'share the connection code', category: 'Screen Sharing Attack', severity: 'CRITICAL' },
      { phrase: 'PAN permanently blacklisted', category: 'Threat Escalation', severity: 'HIGH' },
      { phrase: '2 hours', category: 'Artificial Urgency', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller ID does not match IT Department — spoofed number', timestamp: '00:00:01', triggeredBy: 'Non-government caller ID' },
      { agent: 'NLP Intent Agent', action: 'Tax impersonation scam detected — authority threat + remote access request', timestamp: '00:00:03', triggeredBy: '"tax evasion" + "AnyDesk"' },
      { agent: 'Remote Access Detector Agent', action: 'ALERT: AnyDesk remote access requested — would give full device control', timestamp: '00:00:05', triggeredBy: '"Download the AnyDesk app"' },
      { agent: 'Isolation Pattern Agent', action: 'Isolation via fear of arrest and account freeze', timestamp: '00:00:06', triggeredBy: '"face arrest" + "accounts frozen"' },
      { agent: 'Urgency Detector Agent', action: '2-hour deadline with permanent blacklist threat', timestamp: '00:00:07', triggeredBy: '"within 2 hours"' },
      { agent: 'Evidence Compiler', action: 'Generated remote access scam alert — CRITICAL risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'IT Department Impersonation + Remote Access Scam', content: 'CRITICAL: Fake IT officer demanding AnyDesk installation for "tax verification." AnyDesk would give remote access to your device, allowing complete bank account drain. IT Department never uses AnyDesk or calls for investigations.' },
    ],
    aiAnalysis: {
      confidence: 96.1,
      scamProbability: 98.5,
      threatCategory: 'IT Department Impersonation with Remote Access',
      deepReasoning: 'This is a highly dangerous combination scam: IT department impersonation paired with remote access tool (AnyDesk) installation. If the victim installs AnyDesk and shares the code, the scammer gains complete control of their device, including banking apps, UPI, and all personal data.',
      psychologicalTricks: [
        'Authority impersonation using Income Tax Department',
        'Fabricated tax evasion allegation to create panic',
        'Arrest threat to bypass rational thinking',
        'Anchoring with specific amount (Rs 12,50,000)',
        'Framing remote access as "verification" to normalize it',
        '2-hour deadline to prevent consultation with others',
      ],
      safeActions: [
        'Hang up immediately — do NOT download AnyDesk or any remote access app',
        'IT Department never calls for investigations — they send written notices',
        'Call 1930 to report the scam',
        'If you already installed AnyDesk, uninstall it immediately and disconnect',
        'Contact your bank to secure your accounts',
      ],
      victimBehavior: 'Victims install AnyDesk and share the connection code. Scammers then access banking apps, UPI, and transfer all funds. Average loss: Rs 2,00,000-15,00,000.',
      preventionAdvice: 'IT Department never calls for investigations. They send written notices. Never install remote access tools like AnyDesk at anyone\'s request. No government agency uses AnyDesk.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'IT + Remote Access', score: 97, icon: 'shield', color: '#f43f5e' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Extreme', score: 95, icon: 'brain', color: '#f43f5e' },
        { id: 'urgency', label: 'Urgency Detection', value: 'Critical', score: 96, icon: 'zap', color: '#f43f5e' },
        { id: 'identity', label: 'Identity Impersonation', value: 'IT Officer', score: 94, icon: 'eye', color: '#f43f5e' },
        { id: 'financial', label: 'Financial Threat', value: 'Account Drain', score: 99, icon: 'shield', color: '#f43f5e' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Full Device Access', score: 99, icon: 'lock', color: '#f43f5e' },
      ],
      recommendations: [
        'Hang up immediately — do NOT install AnyDesk',
        'IT Department sends written notices, never calls',
        'Report to 1930 Cyber Crime Helpline',
        'If you installed AnyDesk, uninstall and disconnect immediately',
        'Contact your bank to secure accounts',
      ],
    },
  },
  {
    id: 'remote-access-scam',
    label: 'Remote Access Trojan Scam',
    description: 'Tech support scam installing remote access software on victim device',
    transcript: [
      { speaker: 'SCAMMER', text: 'Hello, this is Microsoft Windows Support. We have detected a virus on your computer that is stealing your banking information.' },
      { speaker: 'SCAMMER', text: 'Your computer IP address has been compromised and is part of a botnet. We need to clean it immediately before your bank accounts are drained.' },
      { speaker: 'SCAMMER', text: 'Please go to anydesk.com and download the remote support tool. I will connect to your computer and remove the virus for free.' },
      { speaker: 'SCAMMER', text: 'Once connected, I will also install our premium antivirus that comes with a 1-year license for Rs 4,999. This will protect all your future transactions.' },
      { speaker: 'SCAMMER', text: 'But you must do this now — the virus is actively stealing data. Every minute you wait, more of your information is being compromised.' },
    ],
    riskLevel: 'CRITICAL',
    finalScore: 95,
    redFlags: [
      { phrase: 'download the remote support tool', category: 'Remote Access Tool', severity: 'CRITICAL' },
      { phrase: 'I will connect to your computer', category: 'Screen Sharing Attack', severity: 'CRITICAL' },
      { phrase: 'premium antivirus for Rs 4,999', category: 'Fake Product Sale', severity: 'HIGH' },
      { phrase: 'virus is actively stealing data', category: 'Fear Induction', severity: 'CRITICAL' },
      { phrase: 'every minute you wait', category: 'Artificial Urgency', severity: 'HIGH' },
      { phrase: 'Microsoft Windows Support', category: 'Authority Impersonation', severity: 'HIGH' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller claiming Microsoft but calling from mobile number — Microsoft does not make outbound calls', timestamp: '00:00:01', triggeredBy: 'Microsoft impersonation via phone' },
      { agent: 'NLP Intent Agent', action: 'Tech support scam pattern — fake virus + remote access + paid product', timestamp: '00:00:03', triggeredBy: 'Multiple scam indicators' },
      { agent: 'Remote Access Detector Agent', action: 'ALERT: AnyDesk remote access requested — would give full device control to scammer', timestamp: '00:00:05', triggeredBy: '"download the remote support tool"' },
      { agent: 'Financial Flow Agent', action: 'Fake antivirus product sale at Rs 4,999 — non-existent product', timestamp: '00:00:06', triggeredBy: '"premium antivirus for Rs 4,999"' },
      { agent: 'Urgency Detector Agent', action: 'Extreme urgency — "every minute" data being stolen', timestamp: '00:00:07', triggeredBy: '"every minute you wait"' },
      { agent: 'Evidence Compiler', action: 'Generated tech support + remote access scam alert — CRITICAL risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'Tech Support + Remote Access Scam', content: 'CRITICAL: Fake Microsoft support requesting AnyDesk installation for "virus removal." Microsoft never makes outbound support calls. AnyDesk would give remote access allowing complete device and bank account compromise.' },
    ],
    aiAnalysis: {
      confidence: 97.3,
      scamProbability: 99.1,
      threatCategory: 'Tech Support + Remote Access Fraud',
      deepReasoning: 'This is a multi-vector scam combining tech support impersonation, fake virus claims, remote access tool installation, and paid fake product sale. Microsoft never makes outbound calls. AnyDesk installation would give the scammer complete control of the victim\'s computer.',
      psychologicalTricks: [
        'Authority impersonation using Microsoft name',
        'Fear induction with "virus stealing banking data"',
        'Free initial service to build trust before paid upsell',
        'Extreme urgency to prevent rational thinking',
        'Anchoring with specific financial threat',
      ],
      safeActions: [
        'Hang up immediately — Microsoft never makes outbound calls',
        'Do NOT download AnyDesk or any remote access tool',
        'Run Windows Defender scan if concerned about viruses',
        'Report the call to Microsoft via their official website',
        'If you installed AnyDesk, uninstall it and run antivirus scan',
      ],
      victimBehavior: 'Victims install AnyDesk, giving scammers remote access. Scammers then install malware, steal credentials, and transfer funds. Average loss: Rs 1,00,000-10,00,000.',
      preventionAdvice: 'Microsoft, Apple, Google never make unsolicited support calls. Never install remote access tools from unknown callers. Use built-in Windows Defender for virus protection.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Tech Support Fraud', score: 98, icon: 'shield', color: '#f43f5e' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'Extreme', score: 93, icon: 'brain', color: '#f43f5e' },
        { id: 'urgency', label: 'Urgency Detection', value: 'Extreme', score: 97, icon: 'zap', color: '#f43f5e' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Microsoft Support', score: 95, icon: 'eye', color: '#f43f5e' },
        { id: 'financial', label: 'Financial Threat', value: 'Full Device + Rs 4,999', score: 99, icon: 'shield', color: '#f43f5e' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Complete', score: 99, icon: 'lock', color: '#f43f5e' },
      ],
      recommendations: [
        'Hang up — Microsoft never makes outbound calls',
        'Do NOT download AnyDesk or remote access tools',
        'Use Windows Defender for virus scanning',
        'If you installed AnyDesk, uninstall immediately',
      ],
    },
  },
  {
    id: 'fake-police-call',
    label: 'Fake Police Verification Call',
    description: 'Scammer impersonating police demanding money for background verification',
    transcript: [
      { speaker: 'SCAMMER', text: 'This is Inspector Arvind from Cyber Crime Cell, Delhi Police. We are conducting a background verification for your passport application.' },
      { speaker: 'SCAMMER', text: 'We found a discrepancy in your address records. There is a pending complaint against your Aadhaar number at the local station.' },
      { speaker: 'SCAMMER', text: 'To clear this, you need to pay a verification fee of Rs 5,000 through UPI. Once paid, we will close the complaint and your passport will be processed normally.' },
      { speaker: 'VICTIM', text: 'I never applied for a passport. There must be a mistake.' },
      { speaker: 'SCAMMER', text: 'Sir, someone may have used your identity fraudulently. If you do not clear this today, an FIR will be registered against you and your name will be in the criminal database.' },
      { speaker: 'SCAMMER', text: 'Do not visit the police station — this matter is being handled at the cyber cell level. Just pay the fee and it will be resolved.' },
    ],
    riskLevel: 'HIGH',
    finalScore: 79,
    redFlags: [
      { phrase: 'verification fee of Rs 5,000', category: 'Advance Fee Fraud', severity: 'CRITICAL' },
      { phrase: 'FIR will be registered', category: 'Legal Threat', severity: 'HIGH' },
      { phrase: 'do not visit the police station', category: 'Isolation Tactic', severity: 'HIGH' },
      { phrase: 'pending complaint against your Aadhaar', category: 'Identity Threat', severity: 'HIGH' },
      { phrase: 'criminal database', category: 'Fear Induction', severity: 'HIGH' },
      { phrase: 'handled at cyber cell level', category: 'Authority Elevation', severity: 'MEDIUM' },
    ],
    agentFires: [
      { agent: 'VoicePrint Agent', action: 'Caller ID does not match Delhi Police — non-official number', timestamp: '00:00:01', triggeredBy: 'Non-police caller ID' },
      { agent: 'NLP Intent Agent', action: 'Police impersonation scam detected — authority threat + fee demand', timestamp: '00:00:03', triggeredBy: '"verification fee" + "FIR"' },
      { agent: 'Financial Flow Agent', action: 'Police never collect fees via UPI — protocol violation', timestamp: '00:00:05', triggeredBy: 'UPI payment to police' },
      { agent: 'Isolation Pattern Agent', action: 'Isolation from police station — "do not visit"', timestamp: '00:00:06', triggeredBy: '"do not visit the police station"' },
      { agent: 'Policy Compliance Agent', action: 'Delhi Police does not conduct passport verification via phone calls', timestamp: '00:00:07', triggeredBy: 'Phone-based verification check' },
      { agent: 'Evidence Compiler', action: 'Generated police impersonation scam alert — HIGH risk', timestamp: '00:00:08', triggeredBy: 'Multiple agent flags' },
    ],
    evidencePackage: [
      { type: 'ALERT', title: 'Police Impersonation Scam Alert', content: 'HIGH: Caller impersonating Delhi Police cyber cell demanding Rs 5,000 verification fee via UPI. Police never collect fees via phone or UPI. Real passport verification is done in-person at the local station.' },
    ],
    aiAnalysis: {
      confidence: 88.7,
      scamProbability: 86.3,
      threatCategory: 'Police Impersonation Fraud',
      deepReasoning: 'The scammer impersonates Delhi Police and creates a fake passport verification scenario. The demand for UPI payment, instruction not to visit the police station, and threat of FIR are all indicators of fraud. Police never collect fees via phone or UPI.',
      psychologicalTricks: [
        'Authority impersonation using police identity',
        'Creating identity theft narrative ("someone used your Aadhaar")',
        'Threatening FIR and criminal record',
        'Isolating from physical police station',
        'Offering "easy resolution" via payment',
      ],
      safeActions: [
        'Do not pay any fees — police never collect via phone',
        'Visit your local police station to verify if there is a real complaint',
        'Call 100 to verify the officer\'s identity',
        'Report the call to cybercrime.gov.in',
        'Police verification is always done in-person',
      ],
      victimBehavior: 'Victims pay to avoid FIR and criminal record, often paying multiple times as scammers escalate. Average loss: Rs 10,000-50,000.',
      preventionAdvice: 'Police verification is always done in-person at the local station. Police never demand UPI payments. Always verify by calling 100 or visiting the station.',
      insights: [
        { id: 'fraud-pattern', label: 'Fraud Pattern', value: 'Police Impersonation', score: 87, icon: 'shield', color: '#f97316' },
        { id: 'emotional', label: 'Emotional Manipulation', value: 'High', score: 82, icon: 'brain', color: '#f97316' },
        { id: 'urgency', label: 'Urgency Detection', value: 'High', score: 80, icon: 'zap', color: '#f97316' },
        { id: 'identity', label: 'Identity Impersonation', value: 'Police Inspector', score: 85, icon: 'eye', color: '#f97316' },
        { id: 'financial', label: 'Financial Threat', value: 'Rs 5,000 UPI', score: 72, icon: 'shield', color: '#f97316' },
        { id: 'data-theft', label: 'Data Theft Risk', value: 'Identity Threat', score: 65, icon: 'lock', color: '#f97316' },
      ],
      recommendations: [
        'Do NOT pay any fees — police never collect via phone',
        'Visit your local police station to verify',
        'Call 100 to verify the officer\'s identity',
        'Report to cybercrime.gov.in',
      ],
    },
  },
];
